#990 create persistent grafana dashboard missing steps for creating in UI
rancher/rancher-docs pull request #1026
Opened 2023-12-08 22:19 UTC by martyav

Fixes #990 

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

From the issue:

> Under the "To create the ConfigMap in the Rancher UI," section, users should be instructed to add the label like the one seen in the example directly above. I have had a customer confused by it (command line did not work) and did not add the label when creating in the UI. This causes it to never import.

> It should also be noted that the user needs to log into the Grafana UI for the dashboards to import, or else they will get permission issues in the logs and it will not import.

## Comments

2023-12-15 16:00 UTC, martyav commented
Reached out to @tlatino on Slack and made some updates.

2023-12-21 22:15 UTC, btat requested changes

2023-12-21 22:15 UTC, btat commented on docs/how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard.md
> +The actual key/value pair may differ if you have modified the Helm chart to watch a different dashboard label and value.
```suggestion
The actual key-value pair may differ if you have modified the Helm chart to watch a different dashboard label and value.
```

Earlier on line 76 the hyphenated form is used.

2023-12-26 16:18 UTC, martyav commented on versioned_docs/version-2.7/how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard.md
> +The actual key/value pair may differ if you have modified the Helm chart to watch a different dashboard label and value.
```suggestion
The actual key-value pair may differ if you have modified the Helm chart to watch a different dashboard label and value.
```

2023-12-26 16:19 UTC, martyav commented on versioned_docs/version-2.8/how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard.md
> +The actual key/value pair may differ if you have modified the Helm chart to watch a different dashboard label and value.
```suggestion
The actual key-value pair may differ if you have modified the Helm chart to watch a different dashboard label and value.
```

2024-01-24 22:14 UTC, btat approved these changes
Approving from a docs/style/formatting perspective.

2024-02-07 22:14 UTC, martyav commented
Merging as this got lost in the holiday shuffle -- it received a technical review already and then got approval on style grounds 2 weeks ago

2024-02-07 22:14 UTC, merged