Enabling "View in API"
rancher/rancher-docs pull request #1047
Opened 2023-12-27 15:56 UTC by sunilarjun

Updating Capturing API section with intructions on enabling the `View in API` button.

Fixes #[issue_number]

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

## Comments

2023-12-27 17:11 UTC, martyav requested changes

2023-12-27 17:11 UTC, martyav commented on docs/pages-for-subheaders/about-the-api.md
> +Additionally, you can use the **View in API** link to view captured Rancher API calls for your respective clusters and resources located in the clickable `⋮` from the UI. This feature is not enabled
```suggestion
### Enable View in API

You can also view captured Rancher API calls for your respective clusters and resources. This feature is not enabled by default. To enable it: 

1. Click on your **User Tile** in the top right corner of the UI and select **Preferences** from the dropdown menu. 
2. Under the **Advanced Features** section, click **Enable "View in API"**
 
Once checked, the **View in API** link will now appear under the **⋮** sub-menu on resource pages in the UI.
```

2023-12-27 17:11 UTC, martyav commented on versioned_docs/version-2.7/pages-for-subheaders/about-the-api.md
> +Additionally, you can use the **View in API** link to view captured Rancher API calls for your respective clusters and resources located in the clickable `⋮` from the UI. This feature is not enabled
```suggestion
### Enable View in API
You can also view captured Rancher API calls for your respective clusters and resources. This feature is not enabled by default. To enable it: 
1. Click on your **User Tile** in the top right corner of the UI and select **Preferences** from the dropdown menu. 
2. Under the **Advanced Features** section, click **Enable "View in API"**
 
Once checked, the **View in API** link will now appear under the **⋮** sub-menu on resource pages in the UI.
```

2023-12-27 17:11 UTC, martyav commented on versioned_docs/version-2.8/pages-for-subheaders/about-the-api.md
> +Additionally, you can use the **View in API** link to view captured Rancher API calls for your respective clusters and resources located in the clickable `⋮` from the UI. This feature is not enabled
```suggestion
### Enable View in API
You can also view captured Rancher API calls for your respective clusters and resources. This feature is not enabled by default. To enable it: 
1. Click on your **User Tile** in the top right corner of the UI and select **Preferences** from the dropdown menu. 
2. Under the **Advanced Features** section, click **Enable "View in API"**
 
Once checked, the **View in API** link will now appear under the **⋮** sub-menu on resource pages in the UI.
```

2023-12-27 18:49 UTC, sunilarjun commented
@martyav Thanks for the review Marty! Just applied the changes.

2023-12-27 20:06 UTC, LucasSaintarbor approved these changes
Small NIT. LGTM 👍

2023-12-27 20:06 UTC, LucasSaintarbor commented on versioned_docs/version-2.7/pages-for-subheaders/about-the-api.md
> +2. Under the **Advanced Features** section, click **Enable "View in API"**
```suggestion

1. Click on your **User Tile** in the top right corner of the UI and select **Preferences** from the dropdown menu. 
2. Under the **Advanced Features** section, click **Enable "View in API"**
```

2023-12-27 20:06 UTC, LucasSaintarbor commented on versioned_docs/version-2.8/pages-for-subheaders/about-the-api.md
> +2. Under the **Advanced Features** section, click **Enable "View in API"**
```suggestion

1. Click on your **User Tile** in the top right corner of the UI and select **Preferences** from the dropdown menu. 
2. Under the **Advanced Features** section, click **Enable "View in API"**
```

2023-12-28 20:42 UTC, martyav approved these changes

2023-12-28 21:17 UTC, merged