Added non-changeable options to rke2-cluster-configuration
rancher/rancher-docs pull request #1053
Opened 2024-01-05 07:03 UTC by danielhass

## Description

This PR adds a notice about non-changeable options with the Rancher RKE2 provisioning. Users can be confused if they add supported RKE2 options to a Rancher cluster config which afterwards aren't reflected in the provisioning process.

`data-dir` for example is such an options that is non-changeable according to RKE2 devs: https://rancher-users.slack.com/archives/C3ASABBD1/p1704389340347459?thread_ts=1704376260.746929&cid=C3ASABBD1

For this option a new paragraph is added that describes that this option will always stay default regardless of the configured value.

2024-01-05 20:53 UTC, btat requested changes
Thanks for the contribution! Just a couple minor language suggestions.

2024-01-05 20:53 UTC, btat commented on docs/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.md
> +- data-dir (Folder to hold state), will always stay the default `/var/lib/rancher/rke2`
```suggestion
- data-dir (folder to hold state), which defaults to `/var/lib/rancher/rke2`.
```

2024-01-05 20:53 UTC, btat commented on docs/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.md
> +There are some configuration options which aren't supported to be changed when provisioning via Rancher:
```suggestion
There are some configuration options that can't be changed when provisioning via Rancher:
```

2024-01-08 14:53 UTC, danielhass commented
@btat - thanks for the review! I added you suggestions.

Maybe we can ping @brandond on a completeness check here? I'm not sure if there are more options that can't be changed when deploying via Rancher?

2024-01-08 18:01 UTC, brandond commented
I don't know what all isn't supported for modification by Rancher. On the RKE2 side, anything that has an option can be configured, it is Rancher that imposes most of the limitations on supported configurations.

2024-01-09 06:42 UTC, danielhass commented
@brandond - thanks for the feedback!

@btat - maybe you know someone from the Rancher team that can check this for completeness? Otherwise I'm fine with it been merge like that of course.

2024-01-09 21:22 UTC, btat commented
@danielhass I'll go ahead and merge this PR and will add a an issue to our backlog about identifying other similar options.

2024-01-09 21:22 UTC, btat approved these changes

2024-01-09 22:16 UTC, merged

2024-01-09 22:30 UTC, brandond commented
@danielhass I would probably defer to someone from the hostbusters team on that?