Update CLI commands for v2.6 - v2.8
rancher/rancher-docs pull request #1058
Opened 2024-01-11 18:48 UTC by LucasSaintarbor

Fixes #198 

## Description

- Update [Rancher CLI command](https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli) for v2.6 - v2.8

- Rancher CLI v2.6.11 
  <img width="1201" alt="Screenshot 2024-01-11 at 10 47 10 AM" src="https://github.com/rancher/rancher-docs/assets/83089978/87a9be62-3765-472c-a65c-db02cf122166">

- Rancher CLI v2.7.7
  <img width="1201" alt="Screenshot 2024-01-11 at 10 47 36 AM" src="https://github.com/rancher/rancher-docs/assets/83089978/df9062cd-0aed-4093-b1ba-c61da82b6ee0">

- Rancher CLI v2.8.0
  <img width="1198" alt="Screenshot 2024-01-11 at 10 46 47 AM" src="https://github.com/rancher/rancher-docs/assets/83089978/5b14d00d-dec2-4573-8136-8c57b56ce161">

## Comments

2024-02-09 19:12 UTC, martyav requested changes
Some typo fixes

2024-02-09 19:12 UTC, martyav commented on docs/reference-guides/cli-with-rancher/rancher-cli.md
> +| `wait`  | Waits for resoruces cluster, app, project, multiClusterApp.  |
```suggestion
| `wait`  | Waits for resources cluster, app, project, multiClusterApp.  |
```

2024-02-09 19:12 UTC, martyav commented on docs/reference-guides/cli-with-rancher/rancher-cli.md
> +| `token`  | Authentictes and generates new kubeconfig token.  |
```suggestion
| `token`  | Authenticates and generates new kubeconfig token.  |
```

2024-02-09 19:12 UTC, martyav commented on versioned_docs/version-2.6/reference-guides/cli-with-rancher/rancher-cli.md
> +| `wait`  | Waits for resoruces cluster, app, project, multiClusterApp.  |
```suggestion
| `wait`  | Waits for resources cluster, app, project, multiClusterApp.  |
```

2024-02-09 19:12 UTC, martyav commented on versioned_docs/version-2.6/reference-guides/cli-with-rancher/rancher-cli.md
> +| `token`  | Authentictes and generates new kubeconfig token.  |
```suggestion
| `token`  | Authenticates and generates new kubeconfig token.  |
```

2024-02-09 19:12 UTC, martyav commented on versioned_docs/version-2.7/reference-guides/cli-with-rancher/rancher-cli.md
> +| `globaldns`  | Performs operations on global DNS providers and entries.  | <!-- Review -->
```suggestion
| `globaldns`  | Performs operations on global DNS providers and entries.  | 
```

I rm'd the comment on the assumption that it was accidentally left in

2024-02-09 19:12 UTC, martyav commented on versioned_docs/version-2.7/reference-guides/cli-with-rancher/rancher-cli.md
> +| `wait`  | Waits for resoruces cluster, app, project, multiClusterApp.  |
```suggestion
| `wait`  | Waits for resources cluster, app, project, multiClusterApp.  |
```

2024-02-09 19:12 UTC, martyav commented on versioned_docs/version-2.7/reference-guides/cli-with-rancher/rancher-cli.md
> +| `token`  | Authentictes and generates new kubeconfig token.  |
```suggestion
| `token`  | Authenticates and generates new kubeconfig token.  |
```

2024-02-09 19:12 UTC, martyav commented on versioned_docs/version-2.8/reference-guides/cli-with-rancher/rancher-cli.md
> +| `wait`  | Waits for resoruces cluster, app, project, multiClusterApp.  |
```suggestion
| `wait`  | Waits for resources cluster, app, project, multiClusterApp.  |
```

2024-02-09 19:12 UTC, martyav commented on versioned_docs/version-2.8/reference-guides/cli-with-rancher/rancher-cli.md
> +| `token`  | Authentictes and generates new kubeconfig token.  |
```suggestion
| `token`  | Authenticates and generates new kubeconfig token.  |
```

2024-02-09 21:47 UTC, btat requested changes

2024-02-09 21:47 UTC, btat commented on versioned_docs/version-2.7/reference-guides/cli-with-rancher/rancher-cli.md
> +| machines, [machine]  | Performs operations on machines.  |
```suggestion
| `machines, [machine]`  | Performs operations on machines.  |
```

2024-02-12 18:58 UTC, LucasSaintarbor commented
@btat @martyav Thanks for reviewing! Added the changes.

2024-02-13 19:09 UTC, merged