add docs for additionalManifest field for RKE2/K3s cluster
rancher/rancher-docs pull request #1063
Opened 2024-01-12 21:07 UTC by jiaqiluo

https://github.com/rancher/rancher/issues/43614

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

This PR is to 
- add docs for the `additionalManifest` filed in RKE2/K3s cluster 
- add links to RKE2/K3s docs for properly using `chartValues` 

## Comments

n/a

2024-01-12 22:07 UTC, martyav requested changes

2024-01-12 22:07 UTC, martyav commented on docs/reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.md
> +The recommended approach is to utilize the `chartValues` field which is explained below.
```suggestion
If you want to customize system charts, you should use the `chartValues` field as described below.

Alternatives, such as using a HelmChartConfig to customize the system charts via `additionalManifest`, can cause unexpected behavior, due to having multiple HelmChartConfigs for the same chart.
```

2024-01-12 22:07 UTC, martyav commented on docs/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.md
> +Specify the addition manifest(s) to be delivered to the control plane nodes.
```suggestion
Specify additional manifests to deliver to the control plane nodes. 
```

2024-01-12 22:07 UTC, martyav commented on versioned_docs/version-2.7/reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.md
> +Specify the addition manifest(s) to be delivered to the control plane nodes.
```suggestion
Specify additional manifests to deliver to the control plane nodes. ```

2024-01-12 22:07 UTC, martyav commented on versioned_docs/version-2.7/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.md
> +Specify the addition manifest(s) to be delivered to the control plane nodes.
```suggestion
Specify additional manifests to deliver to the control plane nodes. ```

2024-01-12 22:07 UTC, martyav commented on versioned_docs/version-2.8/reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.md
> +Specify the addition manifest(s) to be delivered to the control plane nodes.
```suggestion
Specify additional manifests to deliver to the control plane nodes. 
```

2024-01-12 22:07 UTC, martyav commented on versioned_docs/version-2.8/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.md
> +Specify the addition manifest(s) to be delivered to the control plane nodes.
```suggestion
Specify additional manifests to deliver to the control plane nodes. 
```

2024-01-12 22:07 UTC, martyav commented on docs/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.md
> +The recommended approach is to utilize the `chartValues` field which is explained below.
```suggestion
If you want to customize system charts, you should use the `chartValues` field as described below.

Alternatives, such as using a HelmChartConfig to customize the system charts via `additionalManifest`, can cause unexpected behavior, due to having multiple HelmChartConfigs for the same chart.
```

2024-01-12 22:07 UTC, martyav commented on versioned_docs/version-2.7/reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.md
> +The recommended approach is to utilize the `chartValues` field which is explained below.
```suggestion
If you want to customize system charts, you should use the `chartValues` field as described below.

Alternatives, such as using a HelmChartConfig to customize the system charts via `additionalManifest`, can cause unexpected behavior, due to having multiple HelmChartConfigs for the same chart.
```

2024-01-12 22:07 UTC, martyav commented on versioned_docs/version-2.7/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.md
> +The recommended approach is to utilize the `chartValues` field which is explained below.
```suggestion
If you want to customize system charts, you should use the `chartValues` field as described below.

Alternatives, such as using a HelmChartConfig to customize the system charts via `additionalManifest`, can cause unexpected behavior, due to having multiple HelmChartConfigs for the same chart.
```

2024-01-12 22:07 UTC, martyav commented on versioned_docs/version-2.8/reference-guides/cluster-configuration/rancher-server-configuration/k3s-cluster-configuration.md
> +The recommended approach is to utilize the `chartValues` field which is explained below.
```suggestion
If you want to customize system charts, you should use the `chartValues` field as described below.

Alternatives, such as using a HelmChartConfig to customize the system charts via `additionalManifest`, can cause unexpected behavior, due to having multiple HelmChartConfigs for the same chart.
```

2024-01-12 22:07 UTC, martyav commented on versioned_docs/version-2.8/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration.md
> +The recommended approach is to utilize the `chartValues` field which is explained below.
```suggestion
If you want to customize system charts, you should use the `chartValues` field as described below.

Alternatives, such as using a HelmChartConfig to customize the system charts via `additionalManifest`, can cause unexpected behavior, due to having multiple HelmChartConfigs for the same chart.
```

2024-01-12 22:40 UTC, martyav approved these changes

2024-01-13 00:36 UTC, btat approved these changes

2024-01-13 00:36 UTC, merged