Add documentation for customizing the webhook.
rancher/rancher-docs pull request #1081
Opened 2024-01-23 16:32 UTC by KevinJoiner

Fixes https://github.com/rancher/rancher/issues/43621

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description
Rancher added a feature for users to customize webhook values in https://github.com/rancher/rancher/pull/42060, But this feature was never documented. So users are unable to use it effectively.

## Comments

2024-01-23 16:39 UTC, JonCrowther commented on docs/reference-guides/rancher-webhook.md
> +### Customising Rancher-Webhook During Rancher Installation
```suggestion
### Customizing Rancher-Webhook During Rancher Installation
```

2024-01-23 16:39 UTC, JonCrowther commented on docs/reference-guides/rancher-webhook.md
> +One workaround for this issue [documented by Calico](https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking) involves setting `hos
```suggestion
One workaround for this issue [documented by Calico](https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking) involves setting `hostNetwork=true` for the webhook deployment. Users can change this by adding the helm value `global.hostNetwork=true` to the `rancher-config` ConfigMap see [Customizing Rancher-Webhook Configuration](#customizing-rancher-webhook-configuration) for more info.
```

2024-01-23 17:32 UTC, martyav requested changes

2024-01-23 17:32 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +You can customize the local cluster's Rancher-webhook's helm values during the initial Helm installation of the Rancher chart. All values used in the Rancher-Webhook chart can be accessed as nested v
```suggestion
When you use Helm to install the Rancher chart, you can add custom Helm values to the Rancher-Webhook of the local cluster. All values in the Rancher-Webhook chart are accessible as nested variables under the `webhook` name.
```

2024-01-23 17:32 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +These values will be synced to the `rancher-config` ConfigMap during installation.
```suggestion
These values are synced to the `rancher-config` ConfigMap during installation.
```

2024-01-23 17:32 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +**Note:** Helm uses secrets by default to store information. This is a resource that some webhook versions validate. In these cases, directly update the deployment with the hostNetwork=true value usi
```suggestion
**Note:** By default, Helm stores information as secrets. Secrets are a resource that some webhook versions validate. In these cases, directly update the deployment with the `hostNetwork=true` value using kubectl, then update the webhook configuration as specified above.
```

2024-02-01 19:30 UTC, closed without merging

2024-02-01 19:32 UTC, KevinJoiner commented
@JonCrowther Miss you. Also I checked the `Allow edits and access to secrets by maintainers` for you.