Add documentation for customizing the webhook
rancher/rancher-docs pull request #1099
Opened 2024-02-01 19:29 UTC by JonCrowther

Taking over from https://github.com/rancher/rancher-docs/pull/1081

Fixes https://github.com/rancher/rancher/issues/43621

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description
Rancher added a feature for users to customize webhook values in https://github.com/rancher/rancher/pull/42060, But this feature was never documented. So users are unable to use it effectively.

## Comments

Fixes #[issue_number]

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

## Comments

2024-02-01 20:50 UTC, martyav requested changes
Some small spacing issues, plus links to the original edit suggestions in the old PR

2024-02-01 20:50 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +You can add custom Helm values when you install Rancher-Webhook via Helm. During a Helm install of the Rancher-Webhook chart, Rancher checks for custom Helm values. These custom values must be define
See https://github.com/rancher/rancher-docs/pull/1081/files#r1463621623 for edit suggestion history

2024-02-01 20:50 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +When you use Helm to install the Rancher chart, you can add custom Helm values to the Rancher-Webhook of the local cluster. All values in the Rancher-Webhook chart are accessible as nested variables
https://github.com/rancher/rancher-docs/pull/1081/files#r1463652112

2024-02-01 20:50 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +## Customizing Rancher-Webhook Configuration
```suggestion
## Customizing Rancher-Webhook Configuration

```

2024-02-01 20:50 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +```
Suggest adding an extra line break after the triple backticks. I'd add it myself but Github review comments tend to eat the triple backtick syntax...

2024-02-01 20:50 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +### Customizing Rancher-Webhook During Rancher Installation
```suggestion
### Customizing Rancher-Webhook During Rancher Installation

```

2024-02-05 15:49 UTC, martyav approved these changes
Approved, added versioning

2024-02-05 20:24 UTC, martyav commented
@JonCrowther should we merge or do we need a technical review?

2024-02-07 20:02 UTC, JonCrowther commented
@martyav would like one technical review. @nflynt has been added

2024-02-13 21:00 UTC, nflynt approved these changes
:+1:

2024-02-13 21:08 UTC, merged