Update csp-adapter version
rancher/rancher-docs pull request #1133
Opened 2024-02-20 20:27 UTC by mbelur

## Description

Update version support for csp-adapter for 2.7.10 and 2.7.11

2024-02-20 20:44 UTC, martyav commented
Could we update the info just for 2.7.10 and split off the update for 2.7.11 into another PR, so that we can merge it in (and publish) the day of the release?

2024-02-20 20:45 UTC, martyav requested changes

2024-02-20 20:45 UTC, martyav commented on versioned_docs/version-2.7/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
> +| v2.7.11         |     v2.0.4      |
```suggestion
```

Rather have this go out at the same time as the other PRs related to v2.7.11

2024-02-20 21:08 UTC, mbelur commented
> Could we update the info just for 2.7.10 and split off the update for 2.7.11 into another PR, so that we can merge it in (and publish) the day of the release?

Just a quick clarification needed, do I submit the 2.7.10 change PR into the main branch?

2024-02-20 22:49 UTC, martyav commented
> > Could we update the info just for 2.7.10 and split off the update for 2.7.11 into another PR, so that we can merge it in (and publish) the day of the release?
> 
> Just a quick clarification needed, do I submit the 2.7.10 change PR into the main branch?

Yes, if you do that it'll be immediately published once it's merged to main

2024-02-21 00:20 UTC, mbelur commented
> > > Could we update the info just for 2.7.10 and split off the update for 2.7.11 into another PR, so that we can merge it in (and publish) the day of the release?
> > 
> > 
> > Just a quick clarification needed, do I submit the 2.7.10 change PR into the main branch?
> 
> Yes, if you do that it'll be immediately published once it's merged to main

Submitted a new PR 1134

2024-03-04 15:57 UTC, merged