Docusaurus Upgrade v3.1.1
rancher/rancher-docs pull request #1139
Opened 2024-02-22 21:10 UTC by sunilarjun

Updated MDX in English docs pages and  upgraded certain node packages for upgrading Docusaurus to 3.1.1

DRAFT - In Progress

2024-02-26 21:54 UTC, martyav commented
I'm going to check out the branch and look at a local build of the site. For my initial pas, I'll cover the pages in How-to Guides and Integrations in the English version of latest

2024-02-26 23:14 UTC, martyav requested changes
This was my first pass at it, covering 8 pages in the English version of latest. I'll return for more passes, probably taking on ~10-20 pages at a time

2024-02-26 23:14 UTC, martyav commented on docs/integrations-in-rancher/fleet/use-fleet-behind-a-proxy.md
>  | `NO_PROXY`     | 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local |
It feels like each of the values listed here should have backticks:

`127.0.0.0/8`, `10.0.0.0/8`, etc

2024-02-26 23:14 UTC, martyav commented on docs/integrations-in-rancher/monitoring-and-alerting/promql-expressions.md
This section (Node Network Packet) has strikethroughs:

![image](https://github.com/rancher/rancher-docs/assets/19174201/fe3d856d-6622-45a8-b31f-a802aa4ccebc)

2024-02-26 23:14 UTC, martyav commented on docs/integrations-in-rancher/monitoring-and-alerting/promql-expressions.md
Node Network I/O also has strikethroughs.

2024-02-26 23:14 UTC, martyav commented on docs/integrations-in-rancher/monitoring-and-alerting/promql-expressions.md
Congrats on fixing these, btw, HTML tables within tables are not easy to read!

2024-02-27 23:07 UTC, martyav reviewed
Covered up to i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-keycloak-saml.md

I noticed a strange problem with how section headers that contain colons are handled. For the purposes of the right-hand TOC and links, everything after the colon is ignored until there's a space and then it's rendered as normal, so things like "1.1.2 Ensure that the API server pod specification file ownership is set to root:root (Automated)" get rendered as "[...] set to root (Automated)". This isn't a huge deal, but it could break bookmarks to the affected sections.

2024-02-27 23:33 UTC, btat commented
For the self-assessment pages, we'll want to sync with the Security team. They use a script to generate that content, so if it can be fixed at the source that'll be better than us trying to manually catch it a new guide comes out.

2024-02-27 23:39 UTC, btat commented
> Covered up to i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-keycloak-saml.md (14 pages)
> 
> I noticed a strange problem with how section headers that contain colons are handled. For the purposes of the right-hand TOC and links, everything after the colon is ignored until there's a space and then it's rendered as normal, so things like "1.1.2 Ensure that the API server pod specification file ownership is set to root:root (Automated)" get rendered as "[...] set to root (Automated)". This isn't a huge deal, but it could break bookmarks to the affected sections.

The colon issue is likely https://docusaurus.io/docs/next/migration/v3#unintended-usage-of-directives.

2024-02-28 22:35 UTC, martyav requested changes

2024-02-28 22:35 UTC, martyav commented on i18n/zh/docusaurus-plugin-content-docs/current/integrations-in-rancher/monitoring-and-alerting/promql-expressions.md
节点网络数据包 suffers from the strikethrough problem. 节点网络 I/O too

2024-02-28 22:35 UTC, martyav commented on i18n/zh/docusaurus-plugin-content-docs/version-2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-keycloak-saml.md
The command, `openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout myservice.key -out myservice.cert` (in an admonition) should get backticks

2024-02-28 22:35 UTC, martyav commented on i18n/zh/docusaurus-plugin-content-docs/version-2.6/how-to-guides/new-user-guides/kubernetes-cluster-setup/rke2-for-rancher.md
>          curl -sfL https://get.rke2.io | sh -
This line should get backticks

2024-02-28 22:35 UTC, martyav commented on i18n/zh/docusaurus-plugin-content-docs/version-2.6/integrations-in-rancher/fleet-gitops-at-scale/use-fleet-behind-a-proxy.md
>  | `NO_PROXY` | 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local |
Similar comment as elsewhere about surrounding these values with backticks

2024-02-28 22:37 UTC, martyav commented
I covered up through i18n/zh/docusaurus-plugin-content-docs/version-2.6/integrations-in-rancher/fleet-gitops-at-scale/use-fleet-behind-a-proxy.md (about 15 files), but since they're the same files (just in Chinese), they have similar issues.

2025-07-08 21:37 UTC, btat commented
Closing as this is not something we're actively working on and the PR's stale state.

2025-07-08 21:37 UTC, closed without merging