Adding new issue templates
rancher/rancher-docs pull request #117
Opened 2022-09-14 19:46 UTC by jtravee

Adding new issue templates; also updating GH button on docs site.

2022-09-14 23:13 UTC, btat requested changes

2022-09-14 23:13 UTC, btat commented on .github/issue_template/request-an-update.md
> +name: Request an Update
There's a lot of overlap with the template for new features. We may want to make this one more generalized?

2022-09-15 14:28 UTC, jtravee commented on .github/issue_template/request-an-update.md
> +labels: Rancher Manager
Corrected.

2022-09-15 14:28 UTC, jtravee commented on .github/issue_template/request-a-new-feature.md
> +labels: Rancher Manager
Corrected.

2022-09-15 14:28 UTC, jtravee commented on .github/issue_template/request-to-add-item-to-release-notes.md
> +labels: Rancher Manager
Corrected,

2022-09-15 14:29 UTC, jtravee commented on .github/issue_template/request-to-add-item-to-release-notes.md
> +name: Request a Release Note
Removed this item.

2022-09-15 14:29 UTC, jtravee commented on .github/issue_template/request-a-new-feature.md
> +- List/attach all pertinent information, e.g., screenshots, resource requirements, code blocks, workarounds, links, etc.
Rearranged info; removed the term `code blocks`.

2022-09-15 14:30 UTC, jtravee commented
Also updated the sidebar to auto-collapse sidebar categories as discussed.

2022-10-31 16:23 UTC, merged