Update Docs Versions Table for v2.8.3/v2.7.12 Releases
rancher/rancher-docs pull request #1178
Opened 2024-03-15 19:16 UTC by sunilarjun

Adding updated versions list for2.8.3 and 2.7.12 Rancher releases. Additionally updated the headers to title case.

Part of documentation maintenance items.

2024-03-18 15:37 UTC, martyav approved these changes

2024-03-18 17:23 UTC, btat requested changes

2024-03-18 17:23 UTC, btat commented on src/pages/versions.md
> +    <td><center>&#10003;</center></td>
```suggestion
    <td><center>N/A</center></td>
```

2.7.12 is Prime only.

2024-03-26 18:14 UTC, sunilarjun commented on src/pages/versions.md
> +    <td><center>&#10003;</center></td>
Updated, thanks Billy for clarifying!

2024-03-28 22:37 UTC, btat approved these changes

2024-03-28 22:56 UTC, merged