Adding Webhook Mapping for Release 2.8.3
rancher/rancher-docs pull request #1180
Opened 2024-03-15 20:43 UTC by sunilarjun

Updating the Rancher Webhook table for release 2.8.3.

2024-03-18 15:23 UTC, martyav approved these changes

2024-03-18 17:06 UTC, btat approved these changes
@sunilarjun could you also make an update to the instructions on grabbing this value on the parent issue.

2024-03-26 18:18 UTC, sunilarjun commented
> @sunilarjun could you also make an update to the instructions on grabbing this value on the parent issue.

Updated in both 2.8.3/2.7.12 issues

2024-03-26 22:02 UTC, btat requested changes

2024-03-26 22:09 UTC, sunilarjun commented on docs/reference-guides/rancher-webhook.md
> +| v2.8.3          |     v0.4.2      | &check;               | &check;                   |
Sorry I missed this one, just updated. Thanks Billy!

2024-03-26 22:14 UTC, btat approved these changes

2024-03-28 19:50 UTC, merged