Update publish-images.md
rancher/rancher-docs pull request #1254
Opened 2024-04-26 09:35 UTC by super-small-rookie

Add project creation instructions when pushing images and modify step numbers.

Fixes #[issue_number]

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

## Comments

2024-04-29 15:56 UTC, martyav requested changes
Small copyedit.

2024-04-29 15:56 UTC, martyav commented on docs/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/publish-images.md
> +2. Log into your private registry if required:
```suggestion
1. Ensure that the Rancher project is in your private registry.
   If not, you'll see an error message, such as, "project rancher not found".
   
2. Log into your private registry if required:
```

2024-04-30 20:32 UTC, btat requested changes
Can you add more context around your setup and at what step the error is being thrown? Is the concept of a project something specific to your private registry implementation?

2024-05-09 14:36 UTC, martyav commented
@super-small-rookie Hi, not sure if you saw the comment above. Could you answer these questions?

> Can you add more context around your setup and at what step the error is being thrown? Is the concept of a project something specific to your private registry implementation?

2024-05-17 02:54 UTC, super-small-rookie commented
I use the harbor registry, because the script need project which named rancher to push images. The rancher project does not exist in harbor by default, so it return information about project rancher not found. The information may be returned by harbor. I create the project rancher in harbor, then it pushed images well.

2025-07-08 21:34 UTC, btat commented
In the [preceding step where the docs talk about setting up a private registry](https://github.com/rancher/rancher-docs/blob/e8185388581e4354847553b0ce0a06c1592cb77e/docs/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/infrastructure-private-registry.md) there are no references to any specific private registry implementations so changing this subsequent step to assume Harbor is used does not make sense.

2025-07-08 21:34 UTC, closed without merging