Update use-fleet-behind-a-proxy.md
rancher/rancher-docs pull request #1285
Opened 2024-05-14 11:43 UTC by emilianolangella

I can't find "Agent Environment Vars" under the "Advanced Options", but only under "Cluster Configuration":

![Screenshot from 2024-05-14 13-40-55](https://github.com/rancher/rancher-docs/assets/7261878/62df4f25-1d9f-48b6-a465-96f55d4ed172)

2024-05-14 17:59 UTC, martyav commented
@emilianolangella what version are you running? 

I checked an instance running v2.7 and **Agent Environment Variables** is located as described in the current docs. 

If you're on v2.8, then when we update the versioned pages we only need to update v2.8 and not any further back.

2024-05-14 18:20 UTC, emilianolangella commented
I have 2.8.3.

2024-05-20 15:53 UTC, martyav approved these changes

2024-05-23 18:50 UTC, btat requested changes
The layout difference is depends on if RKE or RKE2/K3s is used. We generally use Tabs to differentiate that difference.

2024-05-23 18:57 UTC, btat commented on docs/integrations-in-rancher/fleet/use-fleet-behind-a-proxy.md
>  1. Click **Save**.
I can't make a direct suggestion due to the deleted line, but it should look something like this:

```
<Tabs groupId="k8s-distro">
<TabItem value="RKE2/K3s" default>
1. Click **☰ > Cluster Management**.
1. Go to the cluster where you want to add environment variables and click **⋮ > Edit Config**.
1. Click **Agent Environment Vars** under **Cluster configuration**.
1. Click **Add**.
1. Enter the [required environment variables](#required-environment-variables)
1. Click **Save**.
</TabItem>
<TabItem value="RKE" default>
1. Click **☰ > Cluster Management**.
1. Go to the cluster where you want to add environment variables and click **⋮ > Edit Config**.
1. Click **Advanced Options**.
1. Click **Add Environment Variable**.
1. Enter the [required environment variables](#required-environment-variables)
1. Click **Save**.
</TabItem>
</Tabs>
```

2024-07-09 21:53 UTC, btat commented
Rebased and applied change specified in https://github.com/rancher/rancher-docs/pull/1285#discussion_r1612173303.

cc: @LucasSaintarbor @martyav @sunilarjun

2024-07-09 21:56 UTC, martyav approved these changes
Re-submitting approval

2024-07-09 21:59 UTC, sunilarjun approved these changes

2024-07-09 23:05 UTC, merged