#1281 docker machine link redirects to docker desktop documentation
rancher/rancher-docs pull request #1286
Opened 2024-05-14 14:37 UTC by martyav

Fixes #1281 

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

Upon investigating the original problem, learned that:

1. Docker deprecated Docker Machine in 2021
2. Docker now redirects visitors seeking docs about docker Machine to docs about Docker Desktop
3. Rancher (the org) maintains its own fork of Docker Machine and it is used within Rancher (the software)
4. The Rancher Machine fork links to the original Docker Machine documentation the link intended to point to

## Comments

Original comment from #1281:

> I did a little research. The Docker Machine repo is now archived and the project is deprecated.
> 
> From [docker/machine#4894 (comment)](https://github.com/docker/machine/issues/4894#issuecomment-897601827):
> 
> > We are not actively maintaining this project and see [Docker Desktop](https://www.docker.com/products/docker-desktop) as its successor for container development on macOS and Windows. I've added an item on our [docker/roadmap#245](https://github.com/docker/roadmap/issues/245) where you can leave us feedback.
> 
> From [docker/roadmap#245](https://github.com/docker/roadmap/issues/245):
> 
> > The Docker Machine project started in 2014 to make it easier to setup and run Docker in a virtual machine. One of the major use cases for this was to make it easier to use Docker on macOS and Windows. Since its release in 2016, [Docker Desktop](https://www.docker.com/products/docker-desktop) has been seen as the replacement for Docker Machine to develop with containers on macOS and Windows. Not only does Docker Desktop provide a Docker API endpoint but it also provides transparent handling of file sharing and networking between the host and VM which make container development easier.
> 
> [Rancher: Node Drivers](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers#developing-your-own-node-drivers) contains a link to https://docs.docker.com/machine/ but that page has been removed and the Docker site redirects visitors to https://docs.docker.com/desktop/ instead.
> 
> Curiously enough, Rancher maintains its own fork of Docker Machine at https://github.com/rancher/machine. The README on that repo points to https://gcbw.github.io/docker.github.io/machine/, a mirror of the original Docker Machine docs.
> 
> The Rancher fork notes:
> 
> > This project is intended to be embedded and executed by the full [Rancher](https://github.com/rancher/rancher) product and the stand alone cli functionality will remain but the human use of it will not be the primary focus as we will expect inputs provided by other things like Terraform or UIs.

2024-05-14 17:50 UTC, jiaqiluo approved these changes

2024-05-14 19:51 UTC, sunilarjun approved these changes

2024-05-14 21:31 UTC, btat requested changes
The proposed URL looks like a fork of the repo hosted on a personal (someone outside of SUSE?) GitHub pages site. 

We should point to the GitHub source instead https://github.com/docker/docs/blob/vnext-engine/machine/overview.md.

2024-05-14 21:31 UTC, btat commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.md
> +Refer to the original [Docker Machine documentation](https://gcbw.github.io/docker.github.io/machine/) for details on how to develop your own node drivers.
```suggestion
Refer to the original [Docker Machine documentation](https://github.com/docker/docs/blob/vnext-engine/machine/overview.md) for details on how to develop your own node drivers.
```

2024-05-14 21:31 UTC, btat commented on versioned_docs/version-2.0-2.4/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.md
> +Refer to the original [Docker Machine documentation](https://gcbw.github.io/docker.github.io/machine/) for details on how to develop your own node drivers.
```suggestion
Refer to the original [Docker Machine documentation](https://github.com/docker/docs/blob/vnext-engine/machine/overview.md) for details on how to develop your own node drivers.
```

2024-05-14 21:31 UTC, btat commented on versioned_docs/version-2.5/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.md
> +Refer to the original [Docker Machine documentation](https://gcbw.github.io/docker.github.io/machine/) for details on how to develop your own node drivers.
```suggestion
Refer to the original [Docker Machine documentation](https://github.com/docker/docs/blob/vnext-engine/machine/overview.md) for details on how to develop your own node drivers.
```

2024-05-14 21:31 UTC, btat commented on versioned_docs/version-2.6/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.md
> +Refer to the original [Docker Machine documentation](https://gcbw.github.io/docker.github.io/machine/) for details on how to develop your own node drivers.
```suggestion
Refer to the original [Docker Machine documentation](https://github.com/docker/docs/blob/vnext-engine/machine/overview.md) for details on how to develop your own node drivers.
```

2024-05-14 21:31 UTC, btat commented on versioned_docs/version-2.7/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.md
> +Refer to the original [Docker Machine documentation](https://gcbw.github.io/docker.github.io/machine/) for details on how to develop your own node drivers.
```suggestion
Refer to the original [Docker Machine documentation](https://github.com/docker/docs/blob/vnext-engine/machine/overview.md) for details on how to develop your own node drivers.
```

2024-05-14 21:31 UTC, btat commented on versioned_docs/version-2.8/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/about-provisioning-drivers/manage-node-drivers.md
> +Refer to the original [Docker Machine documentation](https://gcbw.github.io/docker.github.io/machine/) for details on how to develop your own node drivers.
```suggestion
Refer to the original [Docker Machine documentation](https://github.com/docker/docs/blob/vnext-engine/machine/overview.md) for details on how to develop your own node drivers.
```

2024-05-15 16:15 UTC, btat approved these changes

2024-05-15 16:21 UTC, merged