tuning: recommend colocation
rancher/rancher-docs pull request #1289
Opened 2024-05-15 10:59 UTC by moio

## Description

Clarify that in high performance scenarios colocated nodes are expected for the upstream cluster.

## Comments

This applies to all versions current and future - for the time being I changed all files identically and opened this PR against the main branch.

2024-05-15 11:00 UTC, moio commented
cc @CamrynCarter

2024-05-15 19:39 UTC, martyav requested changes
I made some suggestions on the first file that should also be considered for the others.

2024-05-15 19:39 UTC, martyav commented on docs/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> +Although Kubernetes is designed to run nodes and control plane components in different "zones" to attain high availability, doing so can have negative consequences on performance.
```suggestion
To provide high availability, Kubernetes is designed to run nodes and control components in different zones. However, if nodes and control plane components are located in different zones, network traffic may be slower. 
```

2024-05-15 19:39 UTC, martyav commented on docs/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> +In particular, traffic beteween Rancher components and the Kubernetes API is sensitive to network latency, and etcd performance will also be negatively affected between its nodes.
```suggestion
Traffic between Rancher components and the Kubernetes API is especially sensitive to network latency, as is etcd traffic between nodes.
```

2024-05-15 19:39 UTC, martyav commented on docs/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> +Therefore run all upstream node clusters in the same location, and particularly make sure latency between etcd nodes and Rancher is as low as possible.
```suggestion
To improve performance, run all upstream node clusters in the same location. In particular, make sure that latency between etcd nodes and Rancher is as low as possible.
```

2024-05-20 15:17 UTC, martyav requested changes
Just some title capitalization

2024-05-20 15:17 UTC, martyav commented on docs/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> +### Keep all Upstream Cluster Nodes co-located
```suggestion
### Keep All Upstream Cluster Nodes Co-located
```

2024-05-20 15:17 UTC, martyav commented on versioned_docs/version-2.6/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> +### Keep all Upstream Cluster Nodes co-located
```suggestion
### Keep All Upstream Cluster Nodes Co-located
```

2024-05-20 15:17 UTC, martyav commented on versioned_docs/version-2.7/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> +### Keep all Upstream Cluster Nodes co-located
```suggestion
### Keep All Upstream Cluster Nodes Co-located
```

2024-05-20 15:17 UTC, martyav commented on versioned_docs/version-2.8/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> +### Keep all Upstream Cluster Nodes co-located
```suggestion
### Keep All Upstream Cluster Nodes Co-located
```

2024-05-20 15:39 UTC, martyav approved these changes

2024-05-21 23:23 UTC, btat approved these changes

2024-05-23 14:25 UTC, merged