tuning: recommend minimum browser specs
rancher/rancher-docs pull request #1290
Opened 2024-05-15 11:15 UTC by moio

## Description

Clarify that in high scale scenarios additional requirements apply to the machine running the browser that navigates the Rancher UI.

## Comments

This applies to all versions current and future - for the time being I changed all files identically and opened this PR against the main branch.

2024-05-15 11:16 UTC, moio commented
cc @CamrynCarter

2024-05-15 19:16 UTC, martyav requested changes
Just reviewed the file in `/docs`, but suggestions should apply to the others as relevant

2024-05-15 19:16 UTC, martyav commented on docs/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> + - 8 GB RAM
```suggestion
 - 8 GB RAM
```
Added non-breaking space as recc'd by Review Dog

2024-05-15 19:16 UTC, martyav commented on docs/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md
> + - Round-trip time (ping time) from browser to upstream cluster: 150ms or less
```suggestion
 - Total network bandwith to the upstream cluster: 72 Mb/s (equivalent to a single 802.11n Wi-Fi 4 link stream, ~8 MB/s http download throughput)
 - Round-trip time (ping time) from browser to upstream cluster: 150 ms or less
```
More spaces

2024-05-16 07:44 UTC, moio commented
Note I disagree with vale about the ordinal in this case - Intel marketing material and the industry in general uses it ubiquitously to indicate microprocessor architectures. I think spelling out the ordinal would make it less familiar for readers.

eg.
https://www.anandtech.com/show/14782/intel-launches-comet-lakeu-and-comet-lakey-10th-gen-core-for-low-power-laptops

2024-05-16 14:50 UTC, martyav commented
@moio It's a good point, I hesitated on that one. The docs team went over how applicable the OpenSUSE Vale style guide is to our situation last week, and made note of some rules that need adjusting. This probably needs to be updated to something like "Ordinals are preferred when listing tech specs"

2024-05-16 15:24 UTC, martyav approved these changes

2024-05-20 15:06 UTC, martyav approved these changes

2024-05-21 14:59 UTC, merged