Syncing for #1304
rancher/rancher-docs pull request #1314
Opened 2024-05-31 21:20 UTC by martyav

Fixes #[issue_number]

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

This syncs changes across versions for #1304 

## Description

## Comments

2024-05-31 23:04 UTC, btat requested changes

2024-06-04 17:45 UTC, btat reviewed
What's the reason for having a different order for this line?
<= 2.6: `An app ID (also called a client ID)`
>= 2.7: `Client ID (also known as app ID)`

2024-06-04 17:45 UTC, btat commented on versioned_docs/version-2.8/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +- Client ID (also known as app ID)
```suggestion
- Client ID (also known as app ID)
```

2024-06-04 17:45 UTC, btat commented on versioned_docs/version-2.7/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +- Client ID (also known as app ID)
```suggestion
- Client ID (also known as app ID)
```

2024-06-04 17:45 UTC, btat commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +- Client ID (also known as app ID)
```suggestion
- Client ID (also known as app ID)
```

2024-06-04 21:22 UTC, martyav commented
> What's the reason for having a different order for this line? <= 2.6: `An app ID (also called a client ID)` >= 2.7: `Client ID (also known as app ID)`

That wasn't the intention, just pushed a commit to correct the error

2024-06-04 21:31 UTC, btat approved these changes

2024-06-04 21:43 UTC, merged