#1358 Link to 'Settings for etcd tuning' no longer valid
rancher/rancher-docs pull request #1362
Opened 2024-06-27 18:34 UTC by martyav

Fixes #1358

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, remember to add a "MERGE ON RELEASE" label and set the proper milestone.

## Description

From the issue:

> The link points to https://coreos.com/etcd/docs/latest/tuning.html, but with coreos.com no longer existing, this now redirects to [etcd.io](https://etcd.io/). Checking archive.org, it looks like this link was invalidated sometime in 2019, as the first instance I can find that has a valid page is back in [2018](https://web.archive.org/web/20181002050041/https://coreos.com/etcd/docs/latest/tuning.html).

I checked the site the link now redirects to, and found that an updated version of the original Tuning page is now located at https://etcd.io/docs/v3.5/tuning/. I updated the link across the docset, including Chinese language versions.

## Comments

2024-06-27 22:57 UTC, sunilarjun reviewed
Successfully tested the added links, but including possible updates outside of the main scope that could be made to the i18n 2.8/2.7 versions that have a broken link to the "Set Up Cloud Providers" page. Thanks Marty!

2024-06-27 22:57 UTC, sunilarjun commented on i18n/zh/docusaurus-plugin-content-docs/version-2.7/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters/checklist-for-production-ready-clusters.md
>  * 集群节点应位于单个区域内。大多数云厂商在一个区域内提供多个可用区，这可以提高你集群的可用性。任何角色的节点都可以使用多个可用区。如果你使用 (../set-up-cloud-providers/set-up-cloud-providers.md) 资源，请查阅文档以了解限制（即区域存储限制）。
```suggestion
* 集群节点应位于单个区域内。大多数云厂商在一个区域内提供多个可用区，这可以提高你集群的可用性。任何角色的节点都可以使用多个可用区。如果你使用 [Kubernetes Cloud Provider](../set-up-cloud-providers/set-up-cloud-providers.md) 资源，请查阅文档以了解限制（即区域存储限制）。
```

2024-06-27 22:57 UTC, sunilarjun commented on i18n/zh/docusaurus-plugin-content-docs/version-2.8/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/checklist-for-production-ready-clusters/checklist-for-production-ready-clusters.md
>  * 集群节点应位于单个区域内。大多数云厂商在一个区域内提供多个可用区，这可以提高你集群的可用性。任何角色的节点都可以使用多个可用区。如果你使用 (../set-up-cloud-providers/set-up-cloud-providers.md) 资源，请查阅文档以了解限制（即区域存储限制）。
```suggestion
* 集群节点应位于单个区域内。大多数云厂商在一个区域内提供多个可用区，这可以提高你集群的可用性。任何角色的节点都可以使用多个可用区。如果你使用 [Kubernetes Cloud Provider](../set-up-cloud-providers/set-up-cloud-providers.md) 资源，请查阅文档以了解限制（即区域存储限制）。
```

2024-07-02 21:20 UTC, btat requested changes
1. Older Rancher versions provision clusters with older etcd versions. Since the etcd.io docs are versioned, we should link to the version-appropriate etcd docs instead of updating all our links to point to 3.5.

For example,
- The [v2.6.0 support matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-0/) lists 
- The [v2.5.0 support matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-5-0/) lists etcd 3.3 for downstream clusters while [v2.5.16](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-5-16/) lists etcd 3.4.

2. We have another etcd.io/docs link (on how-to-guides/advanced-user-guides/tune-etcd-for-large-installs) that points to the 3.4 docs. The etcd link version should be consistent within each of our own docs versions.

2024-07-08 18:52 UTC, martyav commented
@btat I did a diff of https://etcd.io/docs/v3.3/tuning/ vs https://etcd.io/docs/v3.4/tuning/ and the pages are identical except for the addition of the heading, "When to update the heartbeat interval and election timeout settings", to v3.4. Since in some cases I had to choose between the v3.3 and v3.4 link, I opted for including the earlier version as they're functionally the same. I pushed changes for the English docs. I'll update the international pages and any other pages that include the bad links in a bit

2024-07-08 19:36 UTC, martyav commented
@btat I did a crude search on /docs for "https://etcd.io/docs/v3.4" and found 28 instances. Presumably versioned docs will have about as many each. Should we put the updated links for all instances of outdated etcd.io links in this PR or separate them out for ease of review?

2024-07-08 19:58 UTC, btat commented
> @btat I did a crude search on /docs for "https://etcd.io/docs/v3.4" and found 28 instances. Presumably versioned docs will have about as many each. Should we put the updated links for all instances of outdated etcd.io links in this PR or separate them out for ease of review?

Given that these should just be version number changes, I think it's fine to include it in this PR since this PR has the context for why it's being done. As for ease of review, if you group things by commit it shouldn't affect readability too much since the actual content change is minimal.

2024-07-08 22:17 UTC, btat requested changes
For 2.5 you opted to use the earlier etcd version. For 2.6 the more recent version (3.5) is used, but early 2.6 versions (e.g. [2.6.0](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-6-0/) use 3.4. Is there a content difference between 3.4 and 3.5 to prompt the early vs recent version choice?

2024-07-09 16:08 UTC, martyav commented
Just pushed another URL fix, because at about 3.4 the etcd.io site changed how version numbers are written in the URL, from including a trailing zero to not including a trailing zero, and the site would inconsistently redirect links that still contained the zero.

2024-07-09 20:49 UTC, btat requested changes
- en: lgtm
- zh: doesn't look like the changes are in sync with the English changes. Some examples:
  - In the `current` set there's a mix of 3.4 and 3.5 links whereas it's all 3.5 on the English side. E.g. `i18n/zh/docusaurus-plugin-content-docs/current/how-to-guides/advanced-user-guides/tune-etcd-for-large-installs.md`
  - On the English side `docs/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md` is modified, but `i18n/zh/docusaurus-plugin-content-docs/current/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale.md` is not.

2024-07-10 18:33 UTC, btat approved these changes

2024-07-10 18:42 UTC, merged