Add Versions Table - v2.9.0
rancher/rancher-docs pull request #1395
Opened 2024-07-23 17:54 UTC by LucasSaintarbor

Add the versions table fields for v2.9.0

2024-07-29 22:02 UTC, btat requested changes

2024-07-29 22:02 UTC, btat commented on src/pages/versions.md
> +    <td><center>&#10003;</center></td>
```suggestion
    <td><center>N/A</center></td>
```

This is not a Prime release.

2024-07-30 19:15 UTC, martyav commented
@LucasSaintarbor just a reminder to address Billy's comment and to convert this from a draft to a PR

2024-07-30 21:26 UTC, btat approved these changes

2024-08-01 00:06 UTC, merged