Update Webhook Table - v2.9.0 / Latest
rancher/rancher-docs pull request #1399
Opened 2024-07-23 21:48 UTC by LucasSaintarbor

Updating webhook table with v2.9.0 section.

2024-07-29 22:05 UTC, btat requested changes

2024-07-29 22:05 UTC, btat commented on docs/reference-guides/rancher-webhook.md
> +| v2.9.0          |     v0.5.0      | &check;               | &check;                   |
```suggestion
| v2.9.0          |     v0.5.0      | &cross;               | &check;                   |
```

2024-07-29 22:05 UTC, btat commented on versioned_docs/version-2.9/reference-guides/rancher-webhook.md
> +| v2.9.0          |     v0.5.0      | &check;               | &check;                   |
```suggestion
| v2.9.0          |     v0.5.0      | &cross;               | &check;                   |
```

2024-07-30 19:25 UTC, martyav commented
@LucasSaintarbor similar to the other draft, just reminding you to address comments and convert from a draft by release time

2024-07-30 21:23 UTC, btat approved these changes

2024-08-01 00:06 UTC, merged