Use crds.enabled to install cert-manager
rancher/rancher-docs pull request #1425
Opened 2024-08-08 12:28 UTC by dharmit

Fixes #[issue_number] N/A

## Description

Installing cert-manager using the currently documented command shows the following warning:
```
NOTES:
⚠️  WARNING: `installCRDs` is deprecated, use `crds.enabled` instead.
```

## Comments

2024-08-08 18:08 UTC, martyav commented
@dharmit do you happen to know if this affects multiple Rancher versions? If just one, which one?

2024-08-08 18:45 UTC, btat commented
> @dharmit do you happen to know if this affects multiple Rancher versions? If just one, which one?

This is coming from cert-manager charts >= v1.15.0 and has no dependency on Rancher itself. This will come up for every cert-manager installation example we have where we don't explicitly set a version (that's also < v1.15.0) in which case it defaults to the latest version of the chart. It's safe to assume all instances of our examples fall into this category.

2024-08-13 14:51 UTC, martyav commented
@btat @LucasSaintarbor @sunilarjun could you have a look? I can't approve as I was the last to update the branch

2024-08-13 15:12 UTC, sunilarjun reviewed
Should we update the translation versions in this PR or create another to update those pages? Otherwise, looks good.

2024-08-13 16:41 UTC, btat requested changes
@martyav As pointed out in [this comment](https://github.com/rancher/rancher-docs/pull/1425#issuecomment-2276445648), this only affects cert-manager >= 1.15.0 (which is when `crds.enabled` was introduced). This means the blanket change in 0c56e643ad9dc4bb78939312bc0e3b3d9e6d506a introduces errors since some of our older docs are explicitly installing versions older than 1.15.0.

As for the cases where `crds.enabled` does apply, simply replacing `installCRDs` in the comment line without any context can be confusing. If a user previously used the old value and reads this page it may look like their case is not covered.

2024-08-16 15:06 UTC, dharmit commented
> Should we update the translation versions in this PR or create another to update those pages? Otherwise, looks good.

@sunilarjun I don't know how to add docs for language other than English. I'll need someone's help with that.



> @martyav As pointed out in [this comment](https://github.com/rancher/rancher-docs/pull/1425#issuecomment-2276445648), this only affects cert-manager >= 1.15.0 (which is when `crds.enabled` was introduced). This means the blanket change in [0c56e64](https://github.com/rancher/rancher-docs/commit/0c56e643ad9dc4bb78939312bc0e3b3d9e6d506a) introduces errors since some of our older docs are explicitly installing versions older than 1.15.0.
> 
> As for the cases where `crds.enabled` does apply, simply replacing `installCRDs` in the comment line without any context can be confusing. If a user previously used the old value and reads this page it may look like their case is not covered.

@btat I'm not sure if you are suggesting me to make some changes here.

2024-08-16 18:08 UTC, btat commented
> > Should we update the translation versions in this PR or create another to update those pages? Otherwise, looks good.
> 
> @sunilarjun I don't know how to add docs for language other than English. I'll need someone's help with that.
> 
> > @martyav As pointed out in [this comment](https://github.com/rancher/rancher-docs/pull/1425#issuecomment-2276445648), this only affects cert-manager >= 1.15.0 (which is when `crds.enabled` was introduced). This means the blanket change in [0c56e64](https://github.com/rancher/rancher-docs/commit/0c56e643ad9dc4bb78939312bc0e3b3d9e6d506a) introduces errors since some of our older docs are explicitly installing versions older than 1.15.0.
> > As for the cases where `crds.enabled` does apply, simply replacing `installCRDs` in the comment line without any context can be confusing. If a user previously used the old value and reads this page it may look like their case is not covered.
> 
> @btat I'm not sure if you are suggesting me to make some changes here.

@dharmit My comment was intended for @martyav since during the process of helping sync the update across different versions of our docs, it introduced errors into the older docs (<= 2.6). I believe Marty is already planning to address those, but feel free to make the changes yourself if preferred. As for the translation files, Marty can probably help with those as well. If you're curious, those files are at https://github.com/rancher/rancher-docs/tree/main/i18n/zh/docusaurus-plugin-content-docs.

2024-08-19 20:09 UTC, btat approved these changes

2024-08-19 20:09 UTC, merged