[v2.10.0] Add docs about enable/disable functionality in clusterrepo
rancher/rancher-docs pull request #1462
Opened 2024-09-13 18:11 UTC by rohitsakala

Please check the issue for more details 

### Summary 

- A new feature about enabling and disabling a Helm repository is added. Updating the docs related to it.
- Targeted for 2.10.0

2024-09-16 17:06 UTC, martyav requested changes

2024-09-16 17:06 UTC, martyav commented on docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md
> +A new feature is added to enable and disable a Helm repository. A Helm repository is enabled by default.
```suggestion
Rancher v2.10.0 adds the ability to enable and disable Helm repositories. Helm repositories are enabled by default.
```

2024-09-16 17:06 UTC, martyav commented on docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md
> +1. Find the repository you want to disable, and click **⋮ > Edit YAML**.
We should add how to navigate to the place where repositories are listed

2024-09-16 17:06 UTC, martyav commented on docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md
> +1. When you disable a repository, updates are disabled and new changes to the clusterRepo are not picked up.
```suggestion
1. When you disable a repository, updates are disabled and new changes to the clusterRepo are not applied.
```

2024-09-16 17:06 UTC, martyav commented on docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md
> +To enabled a chart repository:
```suggestion
To enabled a chart repository:

```

2024-09-16 17:06 UTC, martyav commented on docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md
> +1. Set the `enabled` field under `Spec` to false.
```suggestion
1. Set the **Enabled** field under **Spec** to **false**.
```

2024-09-16 17:06 UTC, martyav commented on docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md
> +1. Set the `enabled` field under `Spec` to true.
```suggestion
1. Set the **Enabled** field under **Spec** to **true**.
```

2024-09-16 17:06 UTC, martyav commented on docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md
> +1. Click on **Save**.
```suggestion
1. Click **Save**.
```

2024-09-16 17:06 UTC, martyav commented on docs/how-to-guides/new-user-guides/helm-charts-in-rancher/helm-charts-in-rancher.md
> +1. Click on **Save**.
```suggestion
1. Click **Save**.
```

2024-09-19 17:16 UTC, martyav approved these changes

2024-09-20 20:24 UTC, martyav approved these changes

2024-10-29 21:29 UTC, btat approved these changes

2024-10-29 21:30 UTC, btat commented
Updated base branch since we have a v2.10 release branch now.

Rebased to pick up update incorporating 2.10 directory. Update has been applied to both en/version-2.10 and zh/version-2.10 folders.

@LucasSaintarbor or @sunilarjun could you please take a second look just to make sure the porting was done correctly.

2024-10-29 22:30 UTC, sunilarjun approved these changes
LGTM

2024-10-30 00:07 UTC, merged