Update Rancher CVE Status
rancher/rancher-docs pull request #1493
Opened 2024-09-26 17:59 UTC by pdellamore

2024-09-26 18:07 UTC, macedogm requested changes

2024-09-26 18:07 UTC, macedogm commented on docs/reference-guides/rancher-security/security-advisories-and-cves.md
> +| [CVE-2024-22030](https://github.com/rancher/rancher/security/advisories/GHSA-h4h5-9833-v2p4) | A vulnerability was discovered in Rancher's and Fleet's agents, currently deemed a medium to high seve
```suggestion
| [CVE-2024-22030](https://github.com/rancher/rancher/security/advisories/GHSA-h4h5-9833-v2p4) | A high severity vulnerability was discovered in Rancher's and Fleet's agents that under very specific circumstances allows a malicious actor to take over existing Rancher nodes. The attacker needs to have control of an expired domain or execute a DNS spoofing/hijacking attack against the domain in order to exploit this vulnerability. The targeted domain is the one used as the Rancher URL (the `server-url` of the Rancher cluster). | 19 Sep 2024 | Rancher [v2.9.2](https://github.com/rancher/rancher/releases/tag/v2.9.2), [v2.8.8](https://github.com/rancher/rancher/releases/tag/v2.8.8) and [v2.7.15](https://github.com/rancher/rancher/releases/tag/v2.7.15) |
```

2024-09-26 18:12 UTC, macedogm commented
@pdellamore we also need to update in https://github.com/rancher/rancher-docs/blob/main/versioned_docs/version-2.9/reference-guides/rancher-security/security-advisories-and-cves.md?plain=1#L13 and add to https://github.com/rancher/rancher-docs/blob/main/versioned_docs/version-2.8/reference-guides/rancher-security/security-advisories-and-cves.md?plain=1 and https://github.com/rancher/rancher-docs/blob/main/versioned_docs/version-2.7/reference-guides/rancher-security/security-advisories-and-cves.md?plain=1, please.

2024-09-26 19:18 UTC, macedogm approved these changes
LGTM, made only one final question.

2024-09-26 19:18 UTC, macedogm commented on versioned_docs/version-2.9/reference-guides/rancher-security/security-advisories-and-cves.md
> +| [CVE-2023-32191](https://github.com/rancher/rke/security/advisories/GHSA-6gr4-52w6-vmqx) | An issue was discovered in Rancher versions up to and including 2.7.13 and 2.8.4, in which supported RKE v
Are these additions intended?

2024-09-27 12:39 UTC, pdellamore commented on versioned_docs/version-2.9/reference-guides/rancher-security/security-advisories-and-cves.md
> +| [CVE-2023-32191](https://github.com/rancher/rke/security/advisories/GHSA-6gr4-52w6-vmqx) | An issue was discovered in Rancher versions up to and including 2.7.13 and 2.8.4, in which supported RKE v
IDK. 

I saw that versioned docs for 2.9 were missing some CVEs added in the last sec release. So I felt it would be good to add them (even though they were done only for v2.8 and v2.7). But I can remove them if they are not needed.

2024-09-27 13:30 UTC, macedogm commented on versioned_docs/version-2.9/reference-guides/rancher-security/security-advisories-and-cves.md
> +| [CVE-2023-32191](https://github.com/rancher/rke/security/advisories/GHSA-6gr4-52w6-vmqx) | An issue was discovered in Rancher versions up to and including 2.7.13 and 2.8.4, in which supported RKE v
Okay, thanks for the explanation. Personally, I would leave only the ones that affect 2.9 and avoid including those that don't.

2024-10-01 16:23 UTC, macedogm commented on versioned_docs/version-2.9/reference-guides/rancher-security/security-advisories-and-cves.md
> +[CVE-2024-22030](https://github.com/rancher/rancher/security/advisories/GHSA-h4h5-9833-v2p4) | A high severity vulnerability was discovered in Rancher's agents that under very specific circumstances
```suggestion
| [CVE-2024-22030](https://github.com/rancher/rancher/security/advisories/GHSA-h4h5-9833-v2p4) | A high severity vulnerability was discovered in Rancher's agents that under very specific circumstances allows a malicious actor to take over existing Rancher nodes. The attacker needs to have control of an expired domain or execute a DNS spoofing/hijacking attack against the domain in order to exploit this vulnerability. The targeted domain is the one used as the Rancher URL (the `server-url` of the Rancher cluster). | 19 Sep 2024 | Rancher [v2.9.2](https://github.com/rancher/rancher/releases/tag/v2.9.2), [v2.8.8](https://github.com/rancher/rancher/releases/tag/v2.8.8) and [v2.7.15](https://github.com/rancher/rancher/releases/tag/v2.7.15) |
```

2024-10-01 16:23 UTC, macedogm approved these changes

2024-10-01 20:32 UTC, LucasSaintarbor approved these changes

2024-10-01 20:32 UTC, merged