Update add-tls-secrets.md
rancher/rancher-docs pull request #1495
Opened 2024-10-03 18:41 UTC by celidon

Fixed command to generate CA certificate to match working command from https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/update-rancher-certificate

Old command results in failures

Fixes #[issue_number]

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, remember to add a "MERGE ON RELEASE" label and set the proper milestone.

## Description

## Comments

2024-10-10 23:14 UTC, btat requested changes
Thanks for the fix @celidon. The change LGTM (+1 also for consistency across pages), but submitting my review with 'request changes' since we need to port the update to other versions of the the file. Let us know if you'd like the Docs team to handle that.

Out of curiosity, what failure were you seeing?

2024-10-21 16:17 UTC, celidon commented
@btat Yes please port it across all versions. That'd be awesome.

The errors were that the secret was getting created with the cert being listed essentially twice, so it was an invalid certificate to authenticate against. I believe the error was something like:

`Failed to read certificate. CA not in x509 format`

2024-10-25 21:49 UTC, btat approved these changes

2024-10-25 22:28 UTC, sunilarjun approved these changes
LGTM

2024-10-25 22:29 UTC, merged