updating extensions doc for 2.10
rancher/rancher-docs pull request #1511
Opened 2024-10-16 16:44 UTC by diogoasouza

This PR updates the extensions' doc in the `docs` folder to match the one in `versioned_docs/version-2.9`

2024-10-16 16:48 UTC, rohitsakala requested changes

2024-10-16 16:49 UTC, diogoasouza commented on docs/integrations-in-rancher/rancher-extensions.md
> +Rancher does have a cached file size limit of 20MB. If an extension has a file bigger than that, the cache is disabled and `plugin.noCache` is set to `true`, regardless of user input.
done

2024-10-16 16:49 UTC, rohitsakala submitted a review, later dismissed

2024-10-30 00:09 UTC, btat reviewed
Content change LGTM, but is the the addition to package.json intentional?

2026-05-06 22:52 UTC, btat submitted a review, later dismissed

2026-05-06 23:16 UTC, LucasSaintarbor requested changes
@btat Requesting a small formatting change for the "Importing and Installing Extensions in an Air-gapped Environment" ordered list.

2026-05-06 23:16 UTC, LucasSaintarbor commented on docs/integrations-in-rancher/rancher-extensions.md
> +  - **(Optional)** If the container image is private: [Create](../how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md) a registry secret within the `cattle-ui-plugin-system` namespace
```suggestion
    - **(Optional)** If the container image is private: [Create](../how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md) a registry secret within the `cattle-ui-plugin-system` namespace. Enter the domain of the image address in the **Registry Domain Name** field.
```

2026-05-06 23:16 UTC, LucasSaintarbor commented on docs/integrations-in-rancher/rancher-extensions.md
> +  * **(Optional)** If the container image is private, select the secret you just created from the **Pull Secrets** drop-down menu.
```suggestion
    * **(Optional)** If the container image is private, select the secret you just created from the **Pull Secrets** drop-down menu.
```

2026-05-06 23:16 UTC, LucasSaintarbor commented on docs/integrations-in-rancher/rancher-extensions.md
> +  - **(Optional)** If the container image is private: [Create](../how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md) a registry secret within the `cattle-ui-plugin-system` namespace
@btat When doing the test build, I noticed the extra tab space for this bullet point in this list was required to get the expected formatting:

<img width="808" height="453" alt="Image" src="https://github.com/user-attachments/assets/4d19e61d-3ce8-4c94-898b-3c6cf714dbb0" />

2026-05-06 23:27 UTC, btat commented on docs/integrations-in-rancher/rancher-extensions.md
> +  - **(Optional)** If the container image is private: [Create](../how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md) a registry secret within the `cattle-ui-plugin-system` namespace
Thanks @LucasSaintarbor. Fixed in https://github.com/rancher/rancher-docs/pull/1511/commits/b65bedd4e8cfb79a8d58b19c9253d41469d0ef40 now.

2026-05-06 23:46 UTC, LucasSaintarbor approved these changes

2026-05-07 00:22 UTC, merged