Add disconnected cluster best practices guide
rancher/rancher-docs pull request #1521
Opened 2024-10-24 11:24 UTC by moio

## Description

This came out of a collaboration with SUSE Support (@gboriso, @axeal) to give customer guidance when it comes to disconnected clusters.

2024-11-05 23:12 UTC, btat requested changes
The new disconnected-clusters.md file needs a sidebar entry:
- /docs: https://github.com/rancher/rancher-docs/blob/main/sidebars.js#L844-L848
- /version-2.9: https://github.com/rancher/rancher-docs/blob/main/versioned_sidebars/version-2.9-sidebars.json#L809-L812

2024-11-05 23:12 UTC, btat commented on docs/reference-guides/best-practices/rancher-managed-clusters/disconnected-clusters.md
> +- **Certificate Rotation Considerations**: When designing processes that involve regularly shutting down clusters, whether connected to Rancher or not, keep into account for certificate rotation poli
```suggestion
- **Certificate Rotation Considerations**: When designing processes that involve regularly shutting down clusters, whether connected to Rancher or not, take into account certificate rotation policies. For example, RKE/RKE2/K3s clusters may rotate certificates on startup if they exceeded their lifetime.
```

2024-11-05 23:12 UTC, btat commented on versioned_docs/version-2.9/reference-guides/best-practices/rancher-managed-clusters/disconnected-clusters.md
> +- **Certificate Rotation Considerations**: When designing processes that involve regularly shutting down clusters, whether connected to Rancher or not, keep into account for certificate rotation poli
```suggestion
- **Certificate Rotation Considerations**: When designing processes that involve regularly shutting down clusters, whether connected to Rancher or not, take into account certificate rotation policies. For example, RKE/RKE2/K3s clusters may rotate certificates on startup if they exceeded their lifetime.
```

2024-11-06 08:19 UTC, moio commented
> The new disconnected-clusters.md file needs a sidebar entry:
> 
>     * /docs: [`main`/sidebars.js#L844-L848](https://github.com/rancher/rancher-docs/blob/main/sidebars.js?rgh-link-date=2024-11-05T23%3A12%3A03Z#L844-L848)
> 
>     * /version-2.9: [`main`/versioned_sidebars/version-2.9-sidebars.json#L809-L812](https://github.com/rancher/rancher-docs/blob/main/versioned_sidebars/version-2.9-sidebars.json?rgh-link-date=2024-11-05T23%3A12%3A03Z#L809-L812)

Done

2024-11-06 22:45 UTC, btat approved these changes

2024-11-06 22:46 UTC, merged