Clarify how user search works
rancher/rancher-docs pull request #1525
Opened 2024-10-25 14:46 UTC by weyfonk

This adds a few points which should shed light on how to search users using a drop-down list in Rancher, whether to add users to clusters or to projects.
Context: https://github.com/rancher/dashboard/issues/12358.

Disclaimer: I have not found a way to test rendering for this, as I kept stumbling upon [this issue](https://github.com/yarnpkg/yarn/issues/8734) when building contents locally.

2024-11-06 00:15 UTC, btat requested changes
LGTM, just a few minor nits. Adding my review as "request changes" since this will need to be ported to other versions/languages of our docs. Let us know if help is needed with that.

2024-11-06 00:15 UTC, btat commented on docs/how-to-guides/new-user-guides/add-users-to-projects.md
> +    - Search is prefix-based (eg. a user named `Stan Dard` will appear when searching for `Sta`, but not when searching for `Dar`) and case-sensitive
```suggestion
    - At least 2 characters must be typed in the search box for results to appear.
    - Users can be searched based on their username or display name.
    - Search is prefix-based (e.g., a user named `Stan Dard` will appear when searching for `Sta`, but not when searching for `Dar`) and case-sensitive.
```

2024-11-06 00:15 UTC, btat commented on docs/how-to-guides/new-user-guides/manage-clusters/access-clusters/add-users-to-clusters.md
> +    - Search is prefix-based (eg. a user named `Stan Dard` will appear when searching for `Sta`, but not when searching for `Dar`) and case-sensitive
```suggestion
    - At least 2 characters must be typed in the search box for results to appear.
    - Users can be searched based on their username or display name.
    - Search is prefix-based (e.g., a user named `Stan Dard` will appear when searching for `Sta`, but not when searching for `Dar`) and case-sensitive.
```

2024-11-06 00:15 UTC, btat commented on docs/how-to-guides/new-user-guides/manage-clusters/projects-and-namespaces.md
> +    - Search is prefix-based (eg. a user named `Stan Dard` will appear when searching for `Sta`, but not when searching for `Dar`) and case-sensitive
```suggestion
    - At least 2 characters must be typed in the search box for results to appear.
    - Users can be searched based on their username or display name.
    - Search is prefix-based (e.g., a user named `Stan Dard` will appear when searching for `Sta`, but not when searching for `Dar`) and case-sensitive.
```

2024-11-07 09:00 UTC, weyfonk commented
> LGTM, just a few minor nits. Adding my review as "request changes" since this will need to be ported to other versions/languages of our docs. Let us know if help is needed with that.

Thanks for your feedback, I think I've addressed all of it.
Then come a couple of questions:
* does porting to other versions mean submitting PRs to separate branches, such as `v2.8.10` and `v2.9.4`? Or rather making similar changes to `versioned_docs`? Either way, I'm not entirely sure _which_ versions of Rancher this applies to, beside the most recent minor.
* how do translations work? I can see contents in `i18n`, the only directory there being `zh` so I'd definitely need help with that :sweat_smile:

2025-05-14 23:41 UTC, btat approved these changes
LGTM. Also rebased and backported to v2.8 (en and zh).

2025-05-14 23:55 UTC, LucasSaintarbor approved these changes

2025-05-15 00:20 UTC, merged