Expand on Project Public API workflows
rancher/rancher-docs pull request #1540
Opened 2024-10-31 17:26 UTC by pmatseykanets

## Description

Document additional Public API workflows for Project resource.

## Comments

2024-10-31 19:21 UTC, crobby submitted a review, later dismissed

2024-11-01 18:08 UTC, crobby approved these changes

2024-11-04 09:24 UTC, olblak approved these changes

2024-11-04 10:01 UTC, olblak commented
Apparently @btat or @martyav need to review this pullrequest and only then they can merge it

2024-11-05 01:17 UTC, btat requested changes

2024-11-05 01:17 UTC, btat commented on docs/api/workflows/projects.md
> +Setting the  `field.cattle.io/creator-principal-name` annotation to the user's principal preserves it in a projectroletemplatebinding automatically created for the project owner.
```suggestion

Setting the  `field.cattle.io/creator-principal-name` annotation to the user's principal preserves it in a projectroletemplatebinding automatically created for the project owner.
```

Adding newline for consistency with the rest of the doc. Right now line 50 and 51 renders as continuous line.

2024-11-05 01:17 UTC, btat commented on versioned_docs/version-2.10/api/workflows/projects.md
> +Setting the  `field.cattle.io/creator-principal-name` annotation to the user's principal preserves it in a projectroletemplatebinding automatically created for the project owner.
```suggestion

Setting the  `field.cattle.io/creator-principal-name` annotation to the user's principal preserves it in a projectroletemplatebinding automatically created for the project owner.
```

2024-11-06 17:28 UTC, pmatseykanets commented
@btat Should this PR be opened against v2.10.0 or main branch?

2024-11-06 22:04 UTC, btat commented
@pmatseykanets v2.10.0 is more suitable in this case since there are 2.10 specific changes to `/docs`, which we don't want to publish yet. The `/docs/` folder represents the latest released version, which is currently 2.9 and will represent 2.10 upon its release.

2024-11-06 22:05 UTC, btat approved these changes

2024-11-06 22:05 UTC, merged