update correct location for azure's cloud controller manager manifest
rancher/rancher-docs pull request #1545
Opened 2024-11-05 23:28 UTC by kinarashah

Issue: https://github.com/rancher/rancher/issues/47824

2024-11-05 23:50 UTC, btat requested changes

2024-11-05 23:50 UTC, btat commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/azure.md
> +4. Under **Cluster Configuration > Add-on Config**, add the cloud controller manager manifest show below into **Additional Manifest**.
```suggestion
4. Under **Cluster Configuration > Add-on Config**, add the cloud controller manager manifest shown below into **Additional Manifest**.
```

2025-03-03 22:04 UTC, btat approved these changes

2025-03-03 22:09 UTC, sunilarjun approved these changes

2025-03-03 23:12 UTC, merged