Update csp-adapter version table (rancher release 2.10)
rancher/rancher-docs pull request #1560
Opened 2024-11-12 20:37 UTC by gbuenodevsuse

## Description
This PR updates rancher/docs to the latest csp-adapter version available

2024-11-13 20:01 UTC, LucasSaintarbor requested changes
@gbuenodevsuse Thanks for adding the Adapter Version for v2.10. Requested changes to remove v2.9 entries.

2024-11-13 20:01 UTC, LucasSaintarbor commented on versioned_docs/version-2.10/integrations-in-rancher/cloud-marketplace/aws-cloud-marketplace/install-adapter.md
> +| v2.10.0         | v105.0.0+up5.0.1 |
@gbuenodevsuse May you remove the v2.9 entries? Thanks

2024-11-14 14:43 UTC, gbuenodevsuse commented
@LucasSaintarbor, entries removed as requested!

2024-11-14 18:46 UTC, LucasSaintarbor commented
> @LucasSaintarbor, entries removed as requested!

@gbuenodevsuse Thank you!

2024-11-14 19:01 UTC, LucasSaintarbor approved these changes

2024-11-14 21:41 UTC, sunilarjun approved these changes

2024-11-14 21:41 UTC, merged