2.10.0 release maintenance tasks
rancher/rancher-docs pull request #1565
Opened 2024-11-13 17:44 UTC by LucasSaintarbor

Related to https://github.com/rancher/rancher-docs/issues/1557

## Description

Release v2.10.0 maintenance tasks. Proposed values as of alpha12.

2024-11-13 21:44 UTC, btat requested changes
`Update the CNI popularity table` part is missing still.

2024-11-14 16:06 UTC, LucasSaintarbor commented
> `Update the CNI popularity table` part is missing still.

Add per [407e7a6](https://github.com/rancher/rancher-docs/pull/1565/commits/407e7a674a1324ee9ee820d85684c013a2b59754)

2024-11-14 21:43 UTC, sunilarjun approved these changes
Approving but just noting the date for deprecated-features.md may need to be updated in a subsequent PR

2024-11-18 22:49 UTC, btat approved these changes

2024-11-18 23:58 UTC, merged