Add prerequisite for AKS import
rancher/rancher-docs pull request #1590
Opened 2024-12-11 14:43 UTC by yiannistri

Fixes https://github.com/rancher/aks-operator/issues/743

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, remember to add a "MERGE ON RELEASE" label and set the proper milestone.

## Description

This PR adds a prerequisite as well as a troubleshooting section for importing AKS clusters.

## Comments

2024-12-13 19:05 UTC, LucasSaintarbor requested changes
@yiannistri Made some small changes/suggestions. If these look okay, I'll apply the updates to v2.10/v2.9

2024-12-13 19:05 UTC, LucasSaintarbor commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +* This may occur if your cluster has disabled local accounts. Enable local accounts before attempting to import the cluster again:
```suggestion
  To resolve this issue, enable local accounts before attempting to [import the cluster](#registering-a-cluster) again.
```

2024-12-13 19:05 UTC, LucasSaintarbor commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +  ```
```suggestion
    ```sh
    az aks update --resource-group <resource-group> --name <cluster-name> --enable-local-accounts
    ```
```

2024-12-24 08:19 UTC, mjura approved these changes

2025-01-07 09:34 UTC, furkatgofurov7 approved these changes
Few suggestions

2025-01-07 09:34 UTC, furkatgofurov7 commented on versioned_docs/version-2.10/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +  ```
to align with https://github.com/rancher/rancher-docs/pull/1590/files#r1884359891

```suggestion
  ```sh
```

2025-01-07 09:34 UTC, furkatgofurov7 commented on versioned_docs/version-2.9/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +  ```
```suggestion
  ```sh
```

2025-01-07 09:34 UTC, furkatgofurov7 commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +This section lists some of the most common errors that may occur when importing a cluster, along with steps to troubleshoot them.
```suggestion
This section lists some of the most common errors that may occur when importing a cluster and provides steps to troubleshoot them.
```

2025-01-07 09:34 UTC, furkatgofurov7 commented on versioned_docs/version-2.10/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +This section lists some of the most common errors that may occur when importing a cluster, along with steps to troubleshoot them.
```suggestion
This section lists some of the most common errors that may occur when importing a cluster and provides steps to troubleshoot them.
```

2025-01-08 14:27 UTC, yiannistri commented
@LucasSaintarbor thanks for the review. Please take another look when you get a chance :pray:

2025-01-13 09:26 UTC, salasberryfin approved these changes

2025-01-16 14:45 UTC, yiannistri commented
@LucasSaintarbor @btat @sunilarjun kind reminder to review this when possible :bow:

2025-01-16 17:51 UTC, LucasSaintarbor approved these changes
@yiannistri LGTM, thanks!

2025-01-16 17:52 UTC, merged