Adding section on upgrading Istio in an air-gapped env
rancher/rancher-docs pull request #285
Opened 2022-11-03 14:49 UTC by jtravee

Closes #82 

Pulled from [original docs PR #4167](https://github.com/rancher/docs/pull/4167).

2023-01-25 22:11 UTC, martyav requested changes
I suggested some style guide edits.

2023-01-25 22:11 UTC, martyav commented on docs/pages-for-subheaders/istio.md
> +3. Pull all required images for Istio in the private registry setup that will be used in the air-gapped environment.
```suggestion
3. Pull all required images for Istio into the private registry you will use in the air-gapped environment.
```

2023-01-25 22:11 UTC, martyav commented on docs/pages-for-subheaders/istio.md
> +If not done by this point, you must set the value `installer.releaseMirror.enabled=true` to allow for the upgrade.
```suggestion
If you haven't already, set `installer.releaseMirror.enabled=true` to upgrade Istio.
```

2023-01-26 15:45 UTC, martyav approved these changes

2023-02-07 18:51 UTC, btat approved these changes

2023-02-07 18:52 UTC, merged