Remove outdated reference to members tab
rancher/rancher-docs pull request #359
Opened 2023-01-05 22:07 UTC by martyav

Addressing #57

I updated the latest page and the one pertaining to 2.6.

Older versions of the page (2.5, and 2.0 - 2.4).

2023-01-10 00:25 UTC, btat requested changes
The original issue is looking for updated steps to add project members, but the proposed updates are for cluster members, which is a different concept.

2023-01-17 21:30 UTC, martyav commented
Unless I'm still lost, 2.7 still seems to have a Members tab. However, you arrive there by clicking a context menu next to the **Create Namespace** button. I updated accordingly.
![add-existing-members-add-member-6](https://user-images.githubusercontent.com/19174201/213016150-e7b4d643-6d83-4e32-ae57-b957154ecb81.PNG)

2023-01-19 19:36 UTC, martyav commented
@btat Just confirmed that 2.6 has identical UI: 
![image](https://user-images.githubusercontent.com/19174201/213542791-074387e8-2f10-45ac-ae9e-85fb13484a58.png)

2023-01-19 19:39 UTC, btat approved these changes

2023-01-19 19:40 UTC, merged