Add i18n and Chinese translation
rancher/rancher-docs pull request #40
Opened 2022-09-13 14:58 UTC by vickyhella

2022-09-13 23:24 UTC, btat commented
There are no errors when I build this, but whenever I try to switch to the Chinese docs I get the 'Page Not Found' page.

2022-09-13 23:27 UTC, btat requested changes
There are no errors when I build this, but whenever I try to switch to the Chinese docs I get the 'Page Not Found' page.

2022-09-14 02:13 UTC, vickyhella commented
May I ask did you run `yarn start`? If so, `yarn start` does not work for the non-default locales. As per Docusaurus's Documentation, you can use `yarn run start -- --locale zh` to run the `zh` locale specifically.

I have also temporarily deployed the vk-bilingual branch to Netlify at https://vk-rancher.netlify.app/. You can visit it to see how it looks in production if needed.

![image](https://user-images.githubusercontent.com/63201949/190042440-86f44786-d711-4acd-b893-d65ee57b5472.png)

2022-09-14 16:52 UTC, btat approved these changes

2022-09-14 16:52 UTC, merged