Moving manage-cluster-templates.md into Manage Clusters
rancher/rancher-docs pull request #466
Opened 2023-03-03 21:53 UTC by sunilarjun

Moving manage-cluster-templates.md into Manage Clusters subsection for more intuitive grouping, and cleaned up sidebars, redirect section, and Chinese translation. This PR fixes #404 .

2023-03-06 23:36 UTC, btat requested changes

2023-03-06 23:36 UTC, btat commented on docusaurus.config.js
> +            from: '/how-to-guides/advanced-user-guides/manage-clusters/manage-cluster-templates'
```suggestion
            from: '/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-cluster-templates'
```

Suggestion made assuming the goal is the redirect from where this file was before it got moved/renamed as part of this PR. In any case, it doesn't look like the file was named/located at `/how-to-guides/advanced-user-guides/manage-clusters/manage-cluster-templates` at any point.

2023-03-06 23:36 UTC, btat commented on docusaurus.config.js
> -          },
We probably should leave this block in for now until we decide on some guidelines on how we want to handle redirects in general. This redirect block and most of the ones surrounding it were added as part of the restructuring in https://github.com/rancher/rancher-docs/pull/234. 

Assuming it works then the full redirect chain (after combining with the one being added) would be

`/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/manage-cluster-templates` --> `/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-cluster-templates` --> `/how-to-guides/new-user-guides/manage-clusters/manage-cluster-templates`

2023-03-07 19:16 UTC, sunilarjun commented
Thanks for the review Billy! Pushed the proposed changes

2023-03-07 19:36 UTC, btat commented
> Thanks for the review Billy! Pushed the proposed changes

Ah, looks like the build is failing because of the redirect block I suggested leaving in. That was the wrong suggestion, it should have been only keeping the `from` portion. Add the proper suggestion now.

2023-03-07 19:37 UTC, btat commented on docusaurus.config.js
> +            from: '/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-cluster-templates'
```suggestion
            from: ['/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-cluster-templates', '/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/manage-cluster-templates']
```

2023-03-07 19:54 UTC, sunilarjun commented
Gotcha just applied the new change, thanks for clarifying!

2023-03-07 22:14 UTC, btat approved these changes

2023-03-07 22:14 UTC, merged