Added instructions for enabling Istio CNI on k3s
rancher/rancher-docs pull request #480
Opened 2023-03-08 15:17 UTC by dgiebert

2023-03-08 21:20 UTC, martyav commented
These instructions are so similar to the ones on https://ranchermanager.docs.rancher.com/integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster, that I think we should update that page (and the page title for it) instead. We can format the code block with tabs to display either RKE2 or K3s YAML.

2023-03-08 21:22 UTC, martyav commented
Docusaurus tabs syntax: https://docusaurus.io/docs/markdown-features/tabs

2023-03-09 07:44 UTC, dgiebert commented
This is a very good idea; I will implement it accordingly!

2023-03-09 18:56 UTC, martyav requested changes
I checked to see if the tabs work correctly in a preview build, and they do.

2023-03-09 18:56 UTC, martyav commented on docs/integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.md
> +title: Additional Steps for Installing Istio on an RKE2 and K3s Clusters
```suggestion
title: Additional Steps for Installing Istio on RKE2 and K3s Clusters
```

2023-03-09 19:06 UTC, btat requested changes

2023-03-09 19:06 UTC, btat commented on docs/integrations-in-rancher/istio/configuration-options/install-istio-on-rke2-cluster.md
> +<TabItem value="k3s">
```suggestion
<TabItem value="K3s">
```

2023-03-15 15:36 UTC, martyav approved these changes

2023-03-20 16:28 UTC, btat approved these changes

2023-03-20 16:28 UTC, merged