#462 Add instructions for how to use PSACT
rancher/rancher-docs pull request #489
Opened 2023-03-14 19:08 UTC by martyav

Resolves #462 and extends #479 

The UI needs to be corrected before we add screenshots.

@jiaqiluo I added sections for RKE, RKE2, and K3s as placeholders. Are there any real differences users need to know about?

2023-03-14 21:31 UTC, martyav commented
@jiaqiluo could you also elaborate on the steps to assign a PSA template? I'm not sure how a user would reach the scene in this screenshot, maybe because I don't yet have access to downstream clusters to test yet -- 
![image](https://user-images.githubusercontent.com/19174201/225141699-10911d23-4d3a-46da-83e4-6f19293f9e77.png)

2023-03-14 21:46 UTC, jiaqiluo commented
I hope the following can give you an idea fo where to find the setting. 

Ideally, the UI should show the same name for those two fields on both editing pages. I am going to log a separate UI issue for it.  

### When creating/updating an RKE cluster

assign a PSA template by changing the selection for `Pod Security Admission Configuration Template` under the `Advance Options`:

<details>
<summary>Screenshot </summary>

![screencapture-137-184-10-199-dashboard-c-manager-provisioning-cattle-io-cluster-create-2023-03-14-14_36_01](https://user-images.githubusercontent.com/6218999/225144744-33950868-6e68-4156-86b2-bddfd047ab1a.png)

</details>






### When creating/updating an RKE2/K3s cluster

assign a PSA template by changing the selection for `Default Pod Security Admission` :

<details>
<summary>Screenshot </summary>

![screencapture-137-184-10-199-dashboard-c-manager-provisioning-cattle-io-cluster-fleet-default-rke2-1-2023-03-14-14_37_17](https://user-images.githubusercontent.com/6218999/225144887-c787dad2-5dda-47a0-9075-e2e027428726.png)

</details>

2023-03-17 14:59 UTC, martyav commented
I'm marking this ready for review but we still need to add screenshots once the typo fix is pushed into a release. The version of 2.7.2 that I have on my local still has the typo.

2023-03-17 16:50 UTC, jiaqiluo requested changes

2023-03-17 16:50 UTC, jiaqiluo commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-template.md
> +1. Find the cluster you want to update in the **Clusters** table, and click the **⋮**.
```suggestion
1. Find the cluster you want to update in the **Clusters** table, and click the **⋮**.
1. Select **Edit Config** .
```

2023-03-17 16:50 UTC, jiaqiluo commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-template.md
> +
```suggestion

:::note
You need to update the target cluster to make the new template take effect in that cluster. An update can be triggered by editing and saving the cluster without changing values. 
:::

```

2023-03-17 18:48 UTC, btat requested changes
The RKE1 vs RKE2/K3s instructions sets should be placed in tabs.

Each instruction set is missing the final done/create/save step.

2023-03-17 19:14 UTC, macedogm commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-template.md
> +### Hardening the Cluster
```suggestion
### Hardening an RKE2 Cluster
```

2023-03-17 19:14 UTC, macedogm commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-template.md
> +### Hardening the Cluster
The above is a suggestion, because the CIS profile option is only applicable to RKE2 clusters. Otherwise we must let this clear in some other way.

2023-03-17 19:14 UTC, macedogm commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-template.md
> +If you select the **rancher-restricted** template but don't select a **CIS Profile**, you won't meet required CIS benchmarks. See the [hardening guide](../../../pages-for-subheaders/rancher-security.
```suggestion
If you select the **rancher-restricted** template but don't select a **CIS Profile**, you won't meet required CIS benchmarks. See RKE2's [hardening guide](../../../pages-for-subheaders/rke2-hardening-guide.md) for more details.
```

2023-03-20 21:37 UTC, btat requested changes

2023-03-21 16:51 UTC, martyav commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-template.md
> +---
Updated in [a980849](https://github.com/rancher/rancher-docs/pull/489/commits/a980849ee67f4f041f1f67944c5628a250506a5a)

2023-03-21 16:56 UTC, martyav commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/pod-security-standards.md
> +For a complete file which has all the exemptions you need to run Rancher, please refer to this [sample Admission Configuration](psa-restricted-exemptions.yaml).
Addressed in [a980849](https://github.com/rancher/rancher-docs/pull/489/commits/a980849ee67f4f041f1f67944c5628a250506a5a) and links updated in subsequent commits

2023-03-21 17:07 UTC, jiaqiluo requested changes

2023-03-21 17:07 UTC, jiaqiluo commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-template.md
Duplicated file and should be removed?

2023-03-21 18:33 UTC, martyav commented on docs/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/psa-config-template.md
That's odd -- I don't have that file anymore in my local, so I can't rm it using the command line. I guess I have to delete it through the web interface?

2023-03-21 18:42 UTC, macedogm approved these changes

2023-03-21 18:45 UTC, macedogm commented
LGTM

My only comment is if we should add the same changes added to RKE1 and K3s pages about the `rancher-restricted` and PSA also to [RKE2 hardening guide](https://github.com/rancher/rancher-docs/blob/99da9e844b4370abeea85cccb6e090938e2ee341/docs/pages-for-subheaders/rke2-hardening-guide.md#podsecurity)?

2023-03-22 19:17 UTC, martyav commented
> LGTM
> 
> My only comment is if we should add the same changes added to RKE1 and K3s pages about the `rancher-restricted` and PSA also to [RKE2 hardening guide](https://github.com/rancher/rancher-docs/blob/99da9e844b4370abeea85cccb6e090938e2ee341/docs/pages-for-subheaders/rke2-hardening-guide.md#podsecurity)?

I agree that it's a good idea. I'll make the update in my next commit.

2023-03-23 17:30 UTC, martyav commented
The UI was recently updated to correct the typo noted earlier, in rc7. However, I don't think we strictly need screenshots for this set of instructions.

2023-03-23 17:34 UTC, jiaqiluo approved these changes

2023-03-23 18:12 UTC, btat requested changes

2023-03-24 19:04 UTC, merged