Update install guide to cover PSP.enabled flag for K8s v1.25
rancher/rancher-docs pull request #567
Opened 2023-04-27 14:33 UTC by frank-at-suse

Added callout to include  --set global.cattle.psp.enabled=false to Helm install command for K8s v1.25 or greater.  Also removed stale CertManager reference and updated --version example to show a more recent Rancher version.

2023-04-27 16:53 UTC, martyav requested changes
I made a suggestion about how to present the information.

2023-04-27 16:53 UTC, martyav commented on docs/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster.md
> +:::
```suggestion
- For Kubernetes v1.25 or later, set `global.cattle.psp.enabled` to `false'.
```

I think this is more appropriate as a bullet point.

2023-04-27 16:53 UTC, martyav commented on docs/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster.md
> +
```suggestion
- For Kubernetes v1.25 or later, set `global.cattle.psp.enabled` to `false'.
  
```

2023-04-27 16:53 UTC, martyav commented on docs/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster.md
> +
```suggestion
- For Kubernetes v1.25 or later, set `global.cattle.psp.enabled` to `false'.

```

2023-04-28 11:46 UTC, frank-at-suse commented
Fine with those changes.  Thanks for the input.

2023-04-28 19:22 UTC, martyav approved these changes

2023-04-28 20:38 UTC, martyav commented
@frank-at-suse @btat The reasoning for the seemingly stale cert-manager reference is that some users who find the page are still on 2.6.x and the warning is still relevant to them: https://github.com/rancher/rancher-docs/pull/526#discussion_r1161872773 However, we can certainly change the tense of the note since March 2022 is past.

2023-04-28 20:52 UTC, btat commented
@frank-at-suse @martyav let's revert the cert-manager bit from this PR since it's not the focus and then we can get the PR merged. Marty and I can continue our discussion on the cert-manager piece offline.

2023-04-28 20:56 UTC, frank-at-suse commented
Works for me!

2023-04-28 21:18 UTC, btat approved these changes

2023-04-28 21:52 UTC, merged