Add docs page for rancher-webhook
rancher/rancher-docs pull request #617
Opened 2023-05-24 12:43 UTC by KevinJoiner

Fixes https://github.com/rancher/rancher-docs/issues/580

2023-05-24 14:07 UTC, MbolotSuse requested changes

2023-05-24 14:08 UTC, MbolotSuse commented on docs/reference-guides/rancher-webhook.md
> +The Rancher-Webhook integrates with Kubernetes' extensible admission controllers, as described in the [Kubernetes documentation](https://kubernetes.io/docs/reference/access-authn-authz/extensible-adm
We should also consider not telling people to look at these resources at all, and instead telling them to look for the version of the deployed chart and look at the docs instead.

2023-05-25 16:01 UTC, KevinJoiner commented on docs/reference-guides/rancher-webhook.md
> +The Rancher-Webhook integrates with Kubernetes' extensible admission controllers, as described in the [Kubernetes documentation](https://kubernetes.io/docs/reference/access-authn-authz/extensible-adm
I will update this comment to only convey to the user that rancher-werbhook owns the rancher.cattle.io resource

2023-06-02 15:10 UTC, martyav commented on docs/reference-guides/rancher-webhook.md
> +Rancher-Webhook is crucial for Rancher to protect clusters against malicious attacks and enable various features.
Maybe change "various" to something that emphasizes their importance, like "critical features", "key features", etc

2023-06-22 20:35 UTC, btat commented on docs/reference-guides/rancher-webhook.md
> +One workaround for this issue [documented by calico](https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking) involves setting `hos
```suggestion
One workaround for this issue [documented by Calico](https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks#install-eks-with-calico-networking) involves setting `hostNetwork=true` for the webhook deployment. Users can change this using the Helm commands below on the affected clusters.
```

2023-06-22 23:43 UTC, btat commented
@martyav @LucasSaintarbor please update the corresponding files in versioned_docs/version-2.7 as well before merging.

2023-06-23 21:36 UTC, martyav approved these changes

2023-06-26 21:18 UTC, martyav commented
@KevinJoiner I just noticed this PR is pointing to `main`. Should this point to the release branch -- or should we keep it on `main` since the webhook is already out? If so, we should probably remove the next-release tag to make it clear that this doesn't depend on v2.7.5.

2023-06-27 16:55 UTC, KevinJoiner commented
@martyav This PR targets the main branch because it was the default branch. I don't know what the branching strategy is for the repo. But this documentation applies to all Rancher versions v2.7.0 and greater and does not depend specifically on v2.7.5

2023-06-27 18:04 UTC, martyav commented
@KevinJoiner since it doesn't depend on 2.7.5, we'll keep it on `main`

2023-06-28 21:00 UTC, btat commented
@MbolotSuse Can you please review this again, it's blocking the PR from being merged.

2023-06-28 21:01 UTC, MbolotSuse commented
@btat I dismissed my stale review, you can now merge if you would like.

2023-06-28 21:04 UTC, btat commented
> @btat I dismissed my stale review, you can now merge if you would like.

Thank you!

2023-06-28 21:04 UTC, merged