#669 New flag for GKE ingress
rancher/rancher-docs pull request #685
Opened 2023-06-13 21:13 UTC by martyav

Fixes #669 

I know this needs to be mirrored to versioned_docs/2.7, I just want to verify that the edits look good.

2023-06-13 21:53 UTC, martyav commented
@btat Sorry about that, moved too fast. I'll update accordingly

2023-06-13 22:27 UTC, martyav commented
...and now that you've pointed it out, I think the release note for this also uses `:` instead of `=`.

2023-06-13 23:31 UTC, btat requested changes

2023-06-13 23:31 UTC, btat commented on docs/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/rancher-on-gke.md
> +In Rancher v2.7.5, if you intend to use the default GKE ingress on your cluster, you need to set the following flag:
We need to include that this is only relevant  "when using the default GKE ingress in a cluster not using VPC-native cluster mode (ie `--no-enable-ip-alias` is set) it is incompatible with the ClusterIP type" as per this [comment](https://github.com/rancher/rancher/issues/16061#issuecomment-1579352835).

2023-06-20 22:16 UTC, btat approved these changes

2023-06-21 20:14 UTC, merged