#455 How to set hostNetwork:true for k8s 1.21 and up
rancher/rancher-docs pull request #732
Opened 2023-07-19 21:40 UTC by martyav

Fixes #455 

The information on this existed, but wasn't really linked to directly. This adds links to where in the UI to go, and what to edit.

2023-07-20 22:00 UTC, btat requested changes

2023-07-21 14:10 UTC, martyav commented on docs/how-to-guides/new-user-guides/kubernetes-resources-setup/load-balancer-and-ingress-controller/ingress-configuration.md
> +Because of this change to the controller, the default behavior no longer sets `hostNetwork` to `true`. However, you must set `hostNetwork` to `true` for TCP- and UDP-based Services to work. To do so,
Since the instructions for RKE and RKE2 are slightly different, I think we might need to link to both...

2023-07-26 00:04 UTC, btat commented
@martyav the references linked don't mention RKE2. Could you confirm if it's applicable there. If it is applicable, the YAML input needs to be double checked as well as it may not be the same as RKE1.

2023-08-02 14:59 UTC, martyav commented
@dereknola Hey, Derek. I'm tagging you in because I saw you worked on the RKE2 page I cited. Could you provide a technical review/advice on wording?

2023-08-08 20:56 UTC, martyav commented
Tagging @jiaqiluo in hopes to answer this question:

> @martyav the references linked don't mention RKE2. Could you confirm if it's applicable there. If it is applicable, the YAML input needs to be double checked as well as it may not be the same as RKE1.

2023-08-08 22:05 UTC, jiaqiluo commented
> Tagging @jiaqiluo in hopes to answer this question:
> 
> > @martyav the references linked don't mention RKE2. Could you confirm if it's applicable there. If it is applicable, the YAML input needs to be double checked as well as it may not be the same as RKE1.

hi @martyav, AFAIK, the change of the default value `hostNetwork` from true to false happens on the RKE1 side only.

2023-08-10 23:45 UTC, jiaqiluo approved these changes

2023-08-11 00:03 UTC, btat approved these changes

2023-08-11 00:03 UTC, merged