Update upgrades.md
rancher/rancher-docs pull request #747
Opened 2023-07-27 22:10 UTC by kevinayres

Add consideration for the current 'Rancher Setup' AWS Marketplace offering, which uses the deployment name of 'rancher-setup'.

2023-07-28 15:42 UTC, martyav requested changes

2023-07-28 15:42 UTC, martyav commented on docs/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster/upgrades.md
> +Your deployment name may vary; for example, with the AWS Marketplace offering of Rancher Setup, the deployment name is 'rancher-stable'.
```suggestion
Your deployment name may vary; for example, if you're deploying Rancher through the AWS Marketplace, the deployment name is 'rancher-stable'. 
```

2023-08-01 20:01 UTC, kevinayres commented
It looks like this was resolved but not published yet.  The change looks good - thank you.

2023-08-01 20:31 UTC, martyav approved these changes

2023-08-01 20:32 UTC, martyav commented
@kevinayres before we merge, do you know if the PR changes also relate to v2.6 or earlier?

2023-08-03 16:47 UTC, merged

2023-08-03 16:48 UTC, martyav commented
I decided to merge anyway, since the information probably pertains more heavily to 2.7 than to earlier versions, as it is the latest

2023-08-03 20:59 UTC, kevinayres commented
Apologies - the current 'Rancher Setup' AWS Marketplace offering is 2.6. It will be replaced with a new MP listing of 2.7.5> and hopefully have the correct deployment name. We'll update both the rancher docs and the Getting Started Guide again after the new listing comes out and we find out what deployment name is uses.

2023-08-04 14:06 UTC, martyav commented
@kevinayres No problem. I'll just sync the relevant 2.6 pages