Update rotate-certificates.md
rancher/rancher-docs pull request #779
Opened 2023-08-15 03:47 UTC by donnyyu

Add ca certs rotation via API procedures.

2023-08-15 16:20 UTC, martyav requested changes

2023-08-15 16:32 UTC, martyav approved these changes

2023-08-15 18:13 UTC, martyav commented
There seems to be disagreement over whether instructions for using this endpoint should be included in the docs, as the endpoint might be removed in the future. Although I already approved, we might have to close this.

2023-08-15 22:06 UTC, closed without merging

2023-08-15 23:42 UTC, donnyyu commented
Hi @martyav the only way to rotate ca is via the endpoint API call, the UI method doesn't have the option. Engineering team has confirmed it is the correct way to rotate ca. [SURE-6175]
You can remove the doc if endpoint is definitely removed from rancher, but it hasn't happened. My customer just wants to 
have an official guide that explains how to rotate ca

2023-08-16 14:15 UTC, martyav commented
@donnyyu Sorry to go back and forth on this. In general, instructions for using that endpoint are discouraged. But if rotating the CA can't be performed otherwise, then we might have to make an exception. I'm waiting to hear on how we should move forward.