#773: Add steps to install Rancher Extensions in an air-gapped environment
rancher/rancher-docs pull request #807
Opened 2023-08-24 16:21 UTC by martyav

Fixes #773 

> There is work in progress for SURE-6065 to provide a way to install Rancher Extensions in an air-gapped environment. The approach requires an additional step or two on top of the steps provided in [Air-Gapped Helm CLI Install](https://ranchermanager.docs.rancher.com/pages-for-subheaders/air-gapped-helm-cli-install) page. We should capture those steps to install extensions in this page.

Opted instead to list instructions on the Extensions page and link to the relevant section from the air-gapped install guide.

The Extensions page could use a refresh. I asked the Dashboard team about rewording a note that isn't directly related to this issue: https://github.com/rancher/dashboard/issues/9580

2023-08-28 11:44 UTC, jordojordo approved these changes
lgtm

2023-09-27 21:09 UTC, btat approved these changes

2023-10-05 16:10 UTC, rohitsakala commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. Find the address of the container image you want to import as an extension.
Rancher provides some extensions such as Kubewarden and elemental and we need to tell the user about this. The extensions are available in this container image https://hub.docker.com/r/rancher/ui-plugin-catalog/tags

The latest available tag is recommended to be used and imported.

2023-10-05 16:13 UTC, rohitsakala commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. [Create](../how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md) a registry secret within the `cattle-UI-plugin-system` namespace. Enter the domain of the image address in the **Re
There is not always a secret needed. For example, for publicly available image such as https://hub.docker.com/r/rancher/ui-plugin-catalog/tags, there is no need to secret to be created. Can we mention this somehow ?

2023-10-05 16:17 UTC, rohitsakala requested changes
The Uninstall and Upgrade section needs to include how to upgrade an *Extension Catalog* like how to upgrade to the latest tag of the catalog container image

Upgrading can be in two ways right now 
1. Update the tag in the deployment.yaml 
2. Deleting the current *Extension Catalog* and then readding it using the latest tag. 

 and how to uninstall an *Extension Catalog* like deleting the catalog container image. 
 
 Maybe, we can add a new page for airgap?

2023-10-24 17:01 UTC, rohitsakala commented
@btat are you going to tackle Uninstalling and upgrade in a separate PR ?

2023-10-25 19:48 UTC, martyav commented
@rohitsakala Apologies for the slow response. 

I'm a little confused by the "catalog" terminology. The latest versions of Rancher don't use the term "catalog" in the UI. In public-facing docs we've been using **Apps & Marketplace** instead, starting in v2.5: https://ranchermanager.docs.rancher.com/v2.5/pages-for-subheaders/helm-charts-in-rancher#changes-in-rancher-v25

For reference, this is the latest version of the page that once described the deprecated catalog system: https://ranchermanager.docs.rancher.com/pages-for-subheaders/helm-charts-in-rancher

In the intro of the [Rancher Extensions](https://ranchermanager.docs.rancher.com/integrations-in-rancher/rancher-extensions) page edited here, we distinguish between extensions and apps:

> Extensions are Helm charts that can only be installed once into a cluster; therefore, these charts have been simplified and separated from the general Helm charts listed under Apps.
>
> Examples of built-in Rancher extensions are Fleet, Explorer, and Harvester. Examples of other extensions that use the Extensions API that can be manually added are Kubewarden and Elemental.

So, if we added information about catalogs (Apps), that seems like it should go on https://ranchermanager.docs.rancher.com/pages-for-subheaders/helm-charts-in-rancher in a separate PR. But Kubewarden and Elemental should be described under the Extensions page as they use the Extensions API.

Please correct me if I misunderstood, I want to get everyone on the same page so we can move forward.

2023-10-30 15:05 UTC, martyav commented
> I wanted to know if there are sections on how to upgrade `Extensions` ((the helm repository which contains helm charts) to a new version. or how to delete `Extensions` (the helm repository which contains helm charts) ?

We don't seem to. That material should probably go on https://ranchermanager.docs.rancher.com/pages-for-subheaders/helm-charts-in-rancher or a new subpage under that topic.

2023-10-30 16:55 UTC, rohitsakala commented
@martyav Why do you think we need to have docs for uninstall and upgrade in a separate section and install in separate section ? They should be in one page or atleast under one section right ?

2023-10-30 17:41 UTC, martyav commented
@rohitsakala After reviewing the thread more closely -- the Extensions page in this PR currently describes how to **update** through the UI, but not how to **upgrade**. It also describes how to uninstall extensions, again through the UI. 

If we're adding material that generally applies to deleting/upgrading helm charts or Apps, it should go on https://ranchermanager.docs.rancher.com/pages-for-subheaders/helm-charts-in-rancher. Maybe that's where I misunderstood.

But if it's specific instructions for working with Extensions, it should go on the Extensions page.

2023-10-30 19:00 UTC, rohitsakala commented
@martyav So let me also re-analyze this 

**CRUD of Specific Extension** 
- Example -  Kubewarden or Elemental 
- Creation - Documented in https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions
- Update - Documneted in https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions
- Deletion - Documented in https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions



**CRUD of Extensions Repository**

#### Helm Github Repository (Works in non airgap mode only)
- Creation - Already documented in https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions
- Deletion - Not Documented 
- Update - Not Documented

#### Helm Container Image  (Works in Airgap mode and non airgap mode)
- Creation - Already documented in this PR
- Deletion - Not Documented 
- Updation - Not Documented 


Can you please let me know if this is right?

2023-10-30 21:57 UTC, btat commented
Hi @rohitsakala, Marty and I had a chat and your reanalysis sounds right. I've also added additional comments and a question below.

> **CRUD of Specific Extension**

We've been requested to add separate pages for integrations such as Kubewarden and Elemental. For such integrations that use the extension mechanism, the CRUD content will be a subpage of the integration page (I.e., https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/kubewarden will have a subpages added). I think we can keep this part out of this PR's scope.
 
> **CRUD of Extensions Repository**
> #### Helm Github Repository (Works in non airgap mode only)
>
> #### Helm Container Image (Works in Airgap mode and non airgap mode)

I think we should include these 2 areas as part of this PR.

> The Uninstall and Upgrade section needs to include how to upgrade an Extensions like how to upgrade to the latest tag of the catalog container image
>
> Upgrading can be in two ways right now
> 
> 1. Update the tag in the deployment.yaml
> 2. Deleting the current Extensions and then readding it using the latest tag.

Are these 2 methods required for air-gap environments because the Update method listed on Step 5 of [this section](https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions#installing-extensions) doesn't work for air-gap or are these alternatives/additional methods?

2023-10-31 21:09 UTC, rohitsakala commented
@btat Thank you for the reply. 

The point 5 of https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions#installing-extensions points to the update of a particular extension example kuberwarden. and this is out of the scope of this PR as you mentioned. 

Let me add some information.

**CRUD of Extensions Repository**

#### Helm Github Repository (Works in non airgap mode only)
- Creation - Already documented in https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions
- Deletion - Not Documented 
- Update - Not Documented

#### Helm Container Image  (Works in Airgap mode and non airgap mode)
- Creation - Already documented in this PR
- Deletion - Not Documented 
- Updation - Right now, only updating from deployment.yaml is possible. In an airgap scenario, the users will have to mirror the image into their private registry before doing the update.


Can you please let me know if this is right?

2023-11-01 21:47 UTC, martyav commented
One last question, how would the user "re-add [the extension] using the latest tag", assuming that the user can do so through the UI?

2023-11-01 21:52 UTC, rohitsakala commented
@martyav that tag is always associated with the extension repository, not an extension. 

Helm Container Image (Works in Airgap mode and non airgap mode)

Example of an extension repository - `rancher/ui-plugin-catalog:1.0.1` where 1.0.1 is the tag.

2023-11-17 00:44 UTC, btat submitted a review, later dismissed

2023-11-17 00:44 UTC, btat commented on docs/integrations-in-rancher/rancher-extensions.md
> +If you've upgraded from an older Rancher version to v2.7.0, uninstalled built-in extensions are no longer listed under the **Available** tab, unless you've manually imported them.
```suggestion
In v2.7.0, the built-in extensions will not be displayed under the **Available** tab. Therefore, you will need to manually add the desired repos to install extensions.
```

The original text is to indicate a limitation found in certain versions (2.7.0-2.7.?) where users would expect something that's built-in to be available for selection. The update here changes the meaning to indicate that there's a change in existing behavior. Also, extensions were introduced in 2.7 so there is no upgrade scenario involved.

2023-11-17 04:58 UTC, rohitsakala commented on docs/integrations-in-rancher/rancher-extensions.md
> +### Importing and Installing Extensions in an Air-Gapped Environment
Nit: Importing and Installing Extensions Repository in an Air-Gapped Environment

2023-11-17 04:58 UTC, rohitsakala commented on docs/integrations-in-rancher/rancher-extensions.md
>  ## Uninstalling Extensions
Nit: Uninstalling Extensions Repositories

2023-11-17 12:12 UTC, rohitsakala commented on docs/integrations-in-rancher/rancher-extensions.md
> +### Updating and Upgrading Extensions in an Air-gapped Environment
Updating and Upgrading Extensions Repository

2023-11-17 12:15 UTC, rohitsakala commented on docs/integrations-in-rancher/rancher-extensions.md
> +<!-- TK Waiting for answer -->
Find the deployment 
ui-plugin-catalog

Click on edit config 
change rancher/ui-plugin-catalog:1.0.1 to rancher/ui-plugin-catalog:1.0.2 (1.0.1 and 1.0.2 are just examples)

click on save.

2023-11-17 12:17 UTC, rohitsakala commented on docs/integrations-in-rancher/rancher-extensions.md
> +<!-- TK Waiting for answer -->
Also, they need to mirror the image rancher/ui-plugin-catalog:1.0.2 to their private registry before dpoing this.

2023-11-17 12:17 UTC, rohitsakala commented
**CRUD of Extensions Repository**

#### Helm Github Repository (Works in non-airgap mode only)
- Creation - Already documented in https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions
- Deletion - Documented in this PR
- Update - No need of documentation since it is automatic.

#### Helm Container Image  (Works in Airgap mode and non-airgap mode)
- Creation - Already documented in this PR
- Deletion - Not Documented 
- Updation -  Documented in this PR.

2023-11-17 12:18 UTC, rohitsakala requested changes
Commented

2023-11-17 16:39 UTC, martyav commented on docs/integrations-in-rancher/rancher-extensions.md
> +### Updating and Upgrading Extensions in an Air-gapped Environment
```suggestion
### Updating and Upgrading an Extensions Repository in an Air-gapped Environment
```

2023-11-17 21:30 UTC, jordojordo requested changes

2023-11-17 21:30 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. Find the address of the container image you want to import as an extension. Rancher provides some extensions, such as Kubewarden and Elemental, through the `ui-plugin-catalog` container image at h
Find the address of the container image you want to import as an extension _repository_.

2023-11-17 21:30 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +    * **(Optional)** If the container image is private: [Create](../how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md) a registry secret within the `cattle-UI-plugin-system` namespa
The namespace **must** be all lower case, i.e. `cattle-ui-plugin-system`.

2023-11-17 21:30 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. Click **Delete**.
Why is this section here? You shouldn't need to delete an extension chart from the Installed Apps page.

2023-11-17 21:30 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +Extensions repository that aren't air-gapped are automatically updated. If the repository is air-gapped, you must update it manually.
_Extension repositories_ that aren't air-gapped...

2023-11-17 21:30 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +First, mirror the latest changes to your private repository by following the same steps for initially [importing and installing an extension repository](#importing-and-installing-extensions-in-an-air
...changes to your private _registry_ by following...

2023-11-17 21:30 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. From the namespaces dropdown menu, select **All Namespaces**.
It is unnecessary to select All Namespaces, you should just select the `cattle-ui-plugin-system` namespace.

2023-11-17 21:30 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. Update the **Container image** field with the container of the deployment.
This is slightly confusing, it should read: "Update the Container Image field within the deployment's container with the latest image."

2023-11-17 21:30 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. Find the name of the extension repository you want to delete. Select the checkbox next to the repository name, then click **Delete**.
This section should provide instructions on deleting the Extension Catalog, not the repository. Deleting an imported extension catalog will automatically remove the associated repository, deployment, and service.

2023-11-17 21:33 UTC, jordojordo requested changes

2023-11-17 21:33 UTC, jordojordo commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. Find the name of the extension repository you want to delete. Select the checkbox next to the repository name, then click **Delete**.
Is this related to Air-gapped extension repositories that are created when importing an extension catalog?

2023-11-20 20:30 UTC, martyav commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. Find the address of the container image you want to import as an extension. Rancher provides some extensions, such as Kubewarden and Elemental, through the `ui-plugin-catalog` container image at h
```suggestion
1. Find the address of the container image repository  that you want to import as an extension. Rancher provides some extensions, such as Kubewarden and Elemental, through the `ui-plugin-catalog` container image at https://hub.docker.com/r/rancher/ui-plugin-catalog/tags. You should import and use the latest tagged version of the image to ensure you receive the latest features and security updates.
```

2023-11-20 20:30 UTC, martyav commented on docs/integrations-in-rancher/rancher-extensions.md
> +    * **(Optional)** If the container image is private: [Create](../how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md) a registry secret within the `cattle-UI-plugin-system` namespa
```suggestion
    * **(Optional)** If the container image is private: [Create](../how-to-guides/new-user-guides/kubernetes-resources-setup/secrets.md) a registry secret within the `cattle-ui-plugin-system` namespace. Enter the domain of the image address in the **Registry Domain Name** field.
```

2023-11-20 20:35 UTC, martyav commented on docs/integrations-in-rancher/rancher-extensions.md
> +Extensions repository that aren't air-gapped are automatically updated. If the repository is air-gapped, you must update it manually.
```suggestion
Extensions repositories that aren't air-gapped are automatically updated. If the repository is air-gapped, you must update it manually.
```

2023-11-20 20:35 UTC, martyav commented on docs/integrations-in-rancher/rancher-extensions.md
> +First, mirror the latest changes to your private repository by following the same steps for initially [importing and installing an extension repository](#importing-and-installing-extensions-in-an-air
```suggestion
First, mirror the latest changes to your private registry by following the same steps for initially [importing and installing an extension repository](#importing-and-installing-extensions-in-an-air-gapped-environment).
```

2023-11-20 20:45 UTC, martyav commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. From the namespaces dropdown menu, select **All Namespaces**.
```suggestion
1. From the namespaces dropdown menu, select **cattle-ui-plugin-system**.
```

2023-11-20 20:46 UTC, martyav commented on docs/integrations-in-rancher/rancher-extensions.md
> +1. Update the **Container image** field with the container of the deployment.
```suggestion
1. Update the **Container Image** field within the deployment's container with the latest image.
```

2023-11-24 06:38 UTC, rohitsakala commented
**CRUD of Extensions Repository**

#### Helm Github Repository (Works in non-airgap mode only)
- Creation - Already documented in https://ranchermanager.docs.rancher.com/v2.8/integrations-in-rancher/rancher-extensions
- Deletion - Documented in this PR
- Update - No need for documentation since it is automatic.

#### Helm Container Image  (Works in Airgap mode and non-airgap mode)
- Creation - Already documented in this PR
- Deletion - Not Documented 
- Updation -  Documented in this PR.

@martyav The deletion of Extension Repository through Container Image (helm) is not yet documented. Rest of LGTM.

2023-11-24 06:38 UTC, rohitsakala requested changes
Commented

2023-11-28 07:46 UTC, rohitsakala commented
@martyav There is an option to `Uninstall` the Extension repo container image. 

<img width="1548" alt="Screenshot 2023-11-28 at 1 15 19 PM" src="https://github.com/rancher/rancher-docs/assets/8402361/eac9e971-91d8-4950-8dec-9b96ab1fb2e1">

2023-12-06 19:48 UTC, merged