#795 Update issue templates, add PR template
rancher/rancher-docs pull request #833
Opened 2023-09-08 15:38 UTC by martyav

Addresses this part of #795:

> We should have another look at our issue templates and update them as needed.

This PR adapts the format seen in the [release notes](https://raw.githubusercontent.com/rancherlabs/release-notes/main/.github/PULL_REQUEST_TEMPLATE.md?token=GHSAT0AAAAAACCYXKBERVJVCILWHU54YHIKZH3JVUQ) repo. Instructions are commented out so that the user can leave them in place when they start writing.

Also added a PR template. It encourages users to include an issue number, and reminds them about the release branch and versioning.

2023-09-08 19:00 UTC, sunilarjun reviewed
Just added some style updates that could be included but overall looks good, thanks!

2023-09-13 02:50 UTC, btat requested changes

2023-09-13 02:50 UTC, btat commented on .github/pull_request_template.md
> +Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.
```suggestion
<!-- Reminder
Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.
```

I think we should make the `Reminder` label part of the comment. In the other instances where a header is used we're expecting the PR creator to fill in some information in the template, but that's not case here.

2023-09-13 17:29 UTC, btat approved these changes

2023-09-13 20:38 UTC, merged