add cattle-cluster-agent debug logs
rancher/rancher-docs pull request #842
Opened 2023-09-14 12:40 UTC by felipe-colussi

Fixes: There is no issue that this fix.

It adds documentation for the fix created on this issue: https://github.com/rancher/rancher/issues/42241

## Description

Add to the logs doc the possibility of using Environment Variables to get logs out of the cattle-cluster-agent.

2023-09-14 21:45 UTC, martyav requested changes

2023-09-14 21:45 UTC, martyav commented on docs/troubleshooting/other-troubleshooting-tips/logging.md
> +Just like the `trace` log level above, `cattle-cluster-agent` debug logs can contain sensitive information.
```suggestion
The `cattle-cluster-agent` debug logs may contain sensitive information.
```

2023-09-14 21:45 UTC, martyav commented on docs/troubleshooting/other-troubleshooting-tips/logging.md
> +initialization of the downstream clusters.
```suggestion
The `cattle-cluster-agent` log levels can be set when you initialize the downstream clusters.  
```

2023-09-14 21:45 UTC, martyav commented on docs/troubleshooting/other-troubleshooting-tips/logging.md
> +the log level.
```suggestion
When you create a cluster under **Cluster Configuration > Agent Environment Vars** you can set variables to define the log level.  
```

2023-09-14 21:45 UTC, martyav commented on docs/troubleshooting/other-troubleshooting-tips/logging.md
> +For debug-level `CATTLE_DEBUG` or `RANCHER_DEUBG` must be set to `true`
```suggestion
- Trace-level logging: Set `CATTLE_TRACE` or `RANCHER_TRACE` to `true`

-  Debug-level logging: Set `CATTLE_DEBUG` or `RANCHER_DEUBG` to `true`
```

2023-09-26 16:46 UTC, a-blender commented
Trying to merge unnecessary commits to wrong branch, @felipe-colussi will open a new PR.

2023-09-26 16:46 UTC, closed without merging