[cis-1.24] update rke2-self-assessment-guide
rancher/rancher-docs pull request #860
Opened 2023-09-18 21:31 UTC by andypitcher

This PR is for RKE2 cis-1.24 and partly fixes 

- https://github.com/rancher/rancher-docs/issues/843

## Description

- Update docs/reference-guides/rancher-security/hardening-guides/rke2-hardening-guide/rke2-self-assessment-guide-with-cis-v1.24-k8s-v1.24.md with the recent results of RKE2 hardened scans ran with [security-scan:v0.2.13](https://github.com/rancher/security-scan/releases/tag/v0.2.13).

2023-09-19 21:17 UTC, martyav approved these changes

2023-09-19 23:38 UTC, macedogm requested changes
Some comments:

1. In https://github.com/andypitcher/rancher-docs/blob/rke2-self-assessment-guide-with-cis-1.24/docs/pages-for-subheaders/rancher-hardening-guides.md?plain=1#L38 `CIS v1.23` should be `CIS v1.24`.
2. In https://github.com/andypitcher/rancher-docs/blob/rke2-self-assessment-guide-with-cis-1.24/docs/pages-for-subheaders/rancher-hardening-guides.md?plain=1#L38 the link to the self-assessment guide is broken.
3. In https://github.com/andypitcher/rancher-docs/blob/rke2-self-assessment-guide-with-cis-1.24/docs/pages-for-subheaders/rancher-hardening-guides.md?plain=1#L39 `CIS v1.23` should be `CIS v1.7`.

2023-09-20 16:31 UTC, macedogm approved these changes

2023-09-20 18:51 UTC, andypitcher reviewed
LGTM.

2023-09-20 19:28 UTC, martyav approved these changes

2023-09-20 19:33 UTC, merged