[cis-1.24] update k3s-self-assessment-guide
rancher/rancher-docs pull request #861
Opened 2023-09-18 22:05 UTC by andypitcher

This PR is for K3S cis-1.24 and partly fixes 

- https://github.com/rancher/rancher-docs/issues/843

## Description

- Update docs/reference-guides/rancher-security/hardening-guides/k3s-hardening-guide/k3s-self-assessment-guide-with-cis-v1.24-k8s-v1.24.md with the recent results of K3S hardened scans ran with [security-scan:v0.2.13](https://github.com/rancher/security-scan/releases/tag/v0.2.13).

2023-09-19 21:09 UTC, martyav approved these changes

2023-09-19 23:44 UTC, macedogm requested changes
Some comments:

1. In https://github.com/andypitcher/rancher-docs/blob/k3s-self-assessment-guide-with-cis-1.24/docs/pages-for-subheaders/rancher-hardening-guides.md?plain=1#L47 `CIS v1.23` should be `CIS v1.24`.
2. In https://github.com/andypitcher/rancher-docs/blob/k3s-self-assessment-guide-with-cis-1.24/docs/pages-for-subheaders/rancher-hardening-guides.md?plain=1#L47 the link to the self-assessment guide is broken.
3. In https://github.com/andypitcher/rancher-docs/blob/k3s-self-assessment-guide-with-cis-1.24/docs/pages-for-subheaders/rancher-hardening-guides.md?plain=1#L48 `CIS v1.23` should be `CIS v1.7`.
4. Please check with the Docs team if the versioned docs should also be updated:
   1. https://github.com/andypitcher/rancher-docs/blob/k3s-self-assessment-guide-with-cis-1.24/versioned_docs/version-2.7/pages-for-subheaders/rancher-hardening-guides.md
   2. Possibly changing the files names in https://github.com/andypitcher/rancher-docs/tree/k3s-self-assessment-guide-with-cis-1.24/versioned_docs/version-2.7/reference-guides/rancher-security/hardening-guides/k3s-hardening-guide to match the new files, the update the links in https://github.com/andypitcher/rancher-docs/blob/k3s-self-assessment-guide-with-cis-1.24/versioned_docs/version-2.7/pages-for-subheaders/rancher-hardening-guides.md

2023-09-20 16:27 UTC, macedogm approved these changes

2023-09-20 17:35 UTC, andypitcher reviewed
LGTM

2023-09-20 19:14 UTC, martyav approved these changes

2023-09-20 20:50 UTC, merged