Update aks SURE-6882.md
rancher/rancher-docs pull request #876
Opened 2023-09-25 10:36 UTC by davidstauffer

Fixes #[[SURE-6882](https://jira.suse.com/browse/SURE-6882)]

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

## Comments

2023-09-25 17:43 UTC, martyav reviewed
On the ticket, it's suggested that we model the update after the existing page, https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks#minimum-eks-permissions. 

I think that should include positioning the equivalent sections in the same places as on https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/eks. This makes it easier to browse the docs, as similar pages have similar sections in the same locations. Sections shouldn't be organized in the chronological order that we add them.

So, when updating this page, "Programmatically Creating AKS Clusters" should remain the last section on the page, and "Setting Up the Minimum Permission Role with the Azure Command Line Tool" should come before "Syncing", to match the order on the EKS page. 

Also, the sections "Setting Up the Resource Group with the Azure Command Line Tool" and "Setting Up the Service Principal with the Azure Command Line Tool" should be moved up. There is already a section entitled "Setting Up the Resource Group with the Azure Command Line Tool" (https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks#setting-up-the-service-principal-with-the-azure-command-line-tool), so the new section being added needs to specify that it's for custom Azure roles. "Setting Up the Service Principal with the Azure Command Line Tool" should come after  "Setting Up the Resource Group with the Azure Command Line Tool" and include some mention that it's for Azure custom roles.

2023-09-26 09:36 UTC, mjura requested changes
please add one more permission

2023-09-26 09:36 UTC, mjura commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +        "Microsoft.ContainerService/managedClusters/write",
Please add also
```suggestion
        "Microsoft.ContainerService/managedClusters/delete",
```

2023-09-27 08:23 UTC, mjura requested changes
It seems that write permission is gone, please revert it
```
"Microsoft.ContainerService/managedClusters/write"
```

2023-09-27 08:23 UTC, mjura commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +        "Microsoft.ContainerService/managedClusters/read",
It seems that `write` permission is gone, please revert it

```suggestion
        "Microsoft.ContainerService/managedClusters/read",
        "Microsoft.ContainerService/managedClusters/write"
```

2023-09-27 21:20 UTC, martyav commented
@davidstauffer I just pushed a commit to re-organize the page. I also removed a duplicate section and added the suggestion proposed by @mjura re: "Microsoft.ContainerService/managedClusters/write" permissions

2023-09-28 17:09 UTC, davidstauffer commented
Thanks @martyav , are we ready to merge? :)

2023-09-28 17:27 UTC, martyav requested changes

2023-09-28 17:27 UTC, martyav commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +You can apply the Rancher AKSv2 Role by running this command:
```suggestion
2. Apply the Rancher AKSv2 Role:
```

2023-09-28 17:27 UTC, martyav commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +Verify if the Rancher AKSv2 Role was created:
```suggestion
3. Verify if the Rancher AKSv2 Role was created:
```

2023-09-28 17:31 UTC, martyav commented
@davidstauffer one last thing -- does this apply to any other versions besides 2.7?

2023-09-28 18:25 UTC, davidstauffer commented
Yes, in theory, it should apply as well to previous versions.  This is setting the privileges on the Azure side.  Better to double check with @mjura , if this can be applied to past versions...

2023-09-29 15:30 UTC, davidstauffer commented
I would suggest we merge for now at least to get it in for 2.7. I think our users would highly benefit from the improved docs around that.

2023-09-29 16:04 UTC, martyav commented
@davidstauffer Let me just add the versioned 2.7 page

2023-09-29 16:10 UTC, martyav commented
@davidstauffer I'm getting an error when I try to push to your branch. Could you copy the file over to versioned_docs/version-2.7/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md

2023-10-02 10:05 UTC, davidstauffer commented
I added it as well to the versioned docs. Let me know if that works for you. David

2023-10-02 15:52 UTC, martyav commented
@davidstauffer I think we're ready now. We just need approval from @mjura. You've already addressed the changes requested from their review. If this is a time sensitive ticket I'll dismiss their review as stale, so we can merge.

2023-10-03 10:09 UTC, mjura submitted a review, later dismissed
please remove SUBSCRIPTION_ID from role

2023-10-03 10:09 UTC, mjura commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +          "/subscriptions/f5e1bf9e-ec79-4fc5-8354-53e2fcc0d99f"
Here `f5e1bf9e-ec79-4fc5-8354-53e2fcc0d99f` it should be removed, here should be SUBSCRIPTION_ID

2023-10-03 10:09 UTC, mjura commented on versioned_docs/version-2.7/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-clusters-from-hosted-kubernetes-providers/aks.md
> +          "/subscriptions/f5e1bf9e-ec79-4fc5-8354-53e2fcc0d99f"
Here `f5e1bf9e-ec79-4fc5-8354-53e2fcc0d99f` it should be removed, here should be SUBSCRIPTION_ID

2023-10-03 12:48 UTC, davidstauffer commented
Done @mjura . I think we can now merge @martyav .
Many thanks,
David

2023-10-03 13:57 UTC, merged