[Backport 2.7] Add cattle-cluster-agent trace/debug logs
rancher/rancher-docs pull request #880
Opened 2023-09-26 17:09 UTC by felipe-colussi

This PR Was created to Replace #842.

**Fixes**: There is no issue that this fix.

It adds documentation for the fix created on this issue: https://github.com/rancher/rancher/issues/42241

## Description

Add to the logs doc the possibility of using Environment Variables to get logs out of the cattle-cluster-agent.

2023-09-26 17:16 UTC, a-blender approved these changes
A few nits but lgtm. I'd suggest `when you initialize downstream clusters` because the phrasing otherwise is odd and sounds like a specific cluster instead of a generic comment about log level. Fix formatting extra line 89, extra space 92

2023-09-27 13:54 UTC, martyav commented on docs/troubleshooting/other-troubleshooting-tips/logging.md
> +The `cattle-cluster-agent` log levels can be set when you initialize the downstream clusters.
Per https://github.com/rancher/rancher-docs/pull/880#pullrequestreview-1644812426

2023-09-27 13:55 UTC, martyav requested changes

2023-09-27 13:55 UTC, martyav commented on docs/troubleshooting/other-troubleshooting-tips/logging.md
> +-  Debug-level logging: Set `CATTLE_DEBUG` or `RANCHER_DEUBG` to `true`
```suggestion
- Debug-level logging: Set `CATTLE_DEBUG` or `RANCHER_DEUBG` to `true`
```

2023-09-27 13:55 UTC, martyav commented on docs/troubleshooting/other-troubleshooting-tips/logging.md
> +
```suggestion
```

2023-09-27 20:51 UTC, btat requested changes
Noticed a typo.

1. Since both the debug and trace levels are set using booleans, does the higher log level take priority when both are true?
2. Assuming 1 is true, what happens in the case where both are enabled and then one of them is subsequently disabled. Is the expected behavior that the log level will be set to the remaining one that's true? E.g. When `CATTLE_TRACE=true, CATTLE_DEBUG=true` becomes `CATTLE_TRACE=false, CATTLE_DEBUG=true` is the log level now at debug?

2023-09-27 20:51 UTC, btat commented on docs/troubleshooting/other-troubleshooting-tips/logging.md
> +-  Debug-level logging: Set `CATTLE_DEBUG` or `RANCHER_DEUBG` to `true`
```suggestion
- Debug-level logging: Set `CATTLE_DEBUG` or `RANCHER_DEBUG` to `true`
```

2023-09-28 16:19 UTC, btat approved these changes

2023-09-28 16:45 UTC, martyav approved these changes

2023-09-28 16:45 UTC, merged