Update register-existing-clusters.md
rancher/rancher-docs pull request #899
Opened 2023-10-04 23:04 UTC by kevinayres

Add EKS Anywhere and EKS Anywhere on Bare Metal specifically to satisfy AWS EKS-A Service Ready Designation

Fixes #[issue_number]

## Reminders

- See the [README](../README.md) for more details on how to work with the Rancher docs.

- Verify if changes pertain to other versions of Rancher. If they do, finalize the edits on one version of the page, then apply the edits to the other versions.

- If the pull request is dependent on an upcoming release, make sure to target the release branch instead of `main`.

## Description

## Comments

2023-10-05 19:34 UTC, martyav requested changes

2023-10-05 19:34 UTC, martyav commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +To successfully import or provision EKS, AKS, and GKE Clusters from Rancher, the cluster must have at least one managed node group. EKS-Anywhere, and EKS Anywhere on Bare Metal clusters can be import
```suggestion
To successfully import or provision EKS, AKS, and GKE clusters from Rancher, the cluster must have at least one managed node group. 

EKS-Anywhere, and EKS Anywhere on Bare Metal clusters can be imported into Rancher with an API address and credentials, as with any downstream cluster. 

GKE Autopilot clusters aren't supported. See [Compare GKE Autopilot and Standard](https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison) for more information about the differences between GKE modes.
```

2023-10-23 20:49 UTC, btat requested changes

2023-10-23 20:49 UTC, btat commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +### Elastic Kubernetes Service (EKS), EKS-Anywhere, EKS Anywhere on Bare Metal, Azure Kubernetes Service (AKS), and Google Kubernetes Engine (GKE)
```suggestion
### Elastic Kubernetes Service (EKS), EKS Anywhere, EKS Anywhere on Bare Metal, Azure Kubernetes Service (AKS), and Google Kubernetes Engine (GKE)  
```

https://aws.amazon.com/eks/eks-anywhere doesn't seem to use the hyphenated form.

2023-10-23 20:49 UTC, btat commented on docs/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters.md
> +EKS-Anywhere, and EKS Anywhere on Bare Metal clusters can be imported into Rancher with an API address and credentials, as with any downstream cluster.
```suggestion
EKS Anywhere, and EKS Anywhere on Bare Metal clusters can be imported into Rancher with an API address and credentials, as with any downstream cluster. 
```

2023-10-23 21:56 UTC, btat approved these changes

2023-10-23 22:26 UTC, merged