Update token setting page
rancher/rancher-docs pull request #906
Opened 2023-10-06 14:29 UTC by JonCrowther

## Description

There are two changes to the token settings:

1. https://github.com/rancher/rancher/issues/41919
    - Changes the default values of `auth-token-max-ttl-minutes` and `kubeconfig-default-token-ttl-minutes`
    - They are no longer set to 0, which means they expire now. Removed kubeconfig tokens from the list of tokens with default ttl=0
    - Updated 2 sections to reference the new default of `kubeconfig-default-token-ttl-minutes`
2. https://github.com/rancher/rancher/issues/38535
    - Removed the setting `kubeconfig-token-ttl-minutes`
    - Removed references to it in the docs
    - Where necessary replaced references to it with `kubeconfig-default-token-TTL-minutes` because that's the new value used

## Comments

The deprecated setting followed the deprecation procedure of 2 full minors warning.

2023-10-09 19:57 UTC, martyav approved these changes

2023-10-11 19:59 UTC, martyav commented
@JonCrowther This is for v2.8, right? Can you update the branch this points to accordingly?

2023-10-12 16:58 UTC, btat commented
@JonCrowther there's been a very recent change to our branching/file structure strategy recently so the `main` branch you had originally is actually correct. However, we've introduced a `versioned_docs/version-2.8` directory which is where this update should be placed. I've taken care of the rebase and applying your update to the right file. Sorry for the confusion.

2023-10-16 17:04 UTC, KevinJoiner requested changes

2023-10-16 17:04 UTC, KevinJoiner commented on versioned_docs/version-2.8/reference-guides/about-the-api/api-tokens.md
> -| `kubeconfig-*`    | Kubeconfig token                                                                       |
Did we change the name of the tokens created when `kubeconfig-generate-token` setting is `false`

2023-10-16 17:04 UTC, KevinJoiner commented on versioned_docs/version-2.8/reference-guides/about-the-api/api-tokens.md
> +2. Set the `kubeconfig-default-token-TTL-minutes` setting to the desired duration in minutes. By default, `kubeconfig-default-token-TTL-minutes` is 43200 (30 days).
Since this setting is no longer 1:1 with `kubeconfig-generate-token` we can probably remove this step.

2023-10-26 21:34 UTC, martyav commented on versioned_docs/version-2.8/reference-guides/about-the-api/api-tokens.md
> +2. Set the `kubeconfig-default-token-TTL-minutes` setting to the desired duration in minutes. By default, `kubeconfig-default-token-TTL-minutes` is 43200 (30 days).
```suggestion
```

2023-10-31 12:07 UTC, KevinJoiner commented on versioned_docs/version-2.8/reference-guides/about-the-api/api-tokens.md
> -| `kubeconfig-*`    | Kubeconfig token                                                                       |
nvm, I didn't see the heading of this section this removal is correct.

2023-11-03 18:44 UTC, KevinJoiner approved these changes

2023-11-03 19:20 UTC, merged