Update cert-manager docs for v1.13.1
rancher/rancher-docs pull request #924
Opened 2023-10-13 19:27 UTC by PennyScissors

Fixes #: https://github.com/rancher/rancher-docs/issues/742

2023-10-16 23:56 UTC, prachidamle commented
@martyav / @btat can you review the docs PR pls?

2023-10-17 00:01 UTC, PennyScissors commented
Note I updated the international docs as well, but there may be some sections that need to be updated as I can't do that myself (like the section saying we support cert-manager.io/v1).

2023-10-17 01:19 UTC, btat requested changes
Sorry for the delay, added some suggestions based on the request to use versionless commands from the Slack thread referenced in SURE-6657.

I can handle syncing the changes across the various versions before merging.

2023-10-17 01:19 UTC, btat commented on docs/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/publish-images.md
> +    helm fetch jetstack/cert-manager --version v1.13.1
```suggestion
    helm fetch jetstack/cert-manager
```

2023-10-17 01:19 UTC, btat commented on docs/getting-started/installation-and-upgrade/other-installation-methods/air-gapped-helm-cli-install/publish-images.md
> +   helm fetch jetstack/cert-manager --version v1.13.1
```suggestion
   helm fetch jetstack/cert-manager
```

2023-10-17 01:19 UTC, btat commented on docs/getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-rancher.md
> +kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.crds.yaml
```suggestion
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/<VERSION>/cert-manager.crds.yaml
```

2023-10-17 01:19 UTC, btat commented on docs/getting-started/installation-and-upgrade/other-installation-methods/rancher-behind-an-http-proxy/install-rancher.md
> +  --namespace cert-manager --version v1.13.1 \
```suggestion
  --namespace cert-manager \
```

2023-10-17 01:19 UTC, btat commented on docs/getting-started/installation-and-upgrade/resources/upgrade-cert-manager.md
> +    helm fetch jetstack/cert-manager --version v1.13.1
```suggestion
    helm fetch jetstack/cert-manager
```

2023-10-17 01:19 UTC, btat commented on docs/getting-started/quick-start-guides/deploy-rancher-manager/helm-cli.md
> +kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.crds.yaml
```suggestion
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/<VERSION>/cert-manager.crds.yaml
```

2023-10-17 01:19 UTC, btat commented on docs/getting-started/installation-and-upgrade/resources/upgrade-cert-manager.md
> +      --version v1.13.1
```suggestion
```

Couldn't include it in the suggestion, but the `\` in `--namespace cert-manager \` needs to be dropped too.

2023-10-17 01:19 UTC, btat commented on docs/getting-started/quick-start-guides/deploy-rancher-manager/helm-cli.md
> +  --version v1.13.1
```suggestion
```

Need to drop the <code>`</code> from <code>--create-namespace &grave;</code> too.

2023-10-17 01:19 UTC, btat commented on docs/getting-started/quick-start-guides/deploy-rancher-manager/helm-cli.md
> +  --version v1.13.1
```suggestion
```

Need to drop the `\` from `--create-namespace \` too.

2023-10-17 01:19 UTC, btat commented on docs/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster.md
> +kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.crds.yaml
```suggestion
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/<VERSION>/cert-manager.crds.yaml
```

2023-10-17 01:19 UTC, btat commented on docs/pages-for-subheaders/install-upgrade-on-a-kubernetes-cluster.md
> +  --version v1.13.1
```suggestion
```

Need to drop the `\` from `--create-namespace \` too

2023-10-17 18:32 UTC, martyav requested changes

2023-10-17 18:32 UTC, martyav commented on docs/getting-started/installation-and-upgrade/resources/upgrade-cert-manager.md
> +Rancher is compatible with the API version cert-manager.io/v1 and has been last tested with cert-manager version v1.13.1
```suggestion
Rancher is compatible with the API version cert-manager.io/v1 and was last tested with cert-manager version v1.13.1
```

2023-10-17 19:24 UTC, PennyScissors commented on docs/getting-started/installation-and-upgrade/resources/upgrade-cert-manager.md
> +
This line needs to be translated and added to the international docs

2023-10-17 21:31 UTC, btat approved these changes

2023-10-17 21:32 UTC, btat commented
@btat note to self, sync versions before merging.

2023-10-18 16:16 UTC, PennyScissors commented
@btat Can I merge this?

2023-10-18 16:34 UTC, btat commented
> @btat Can I merge this?

@PennyScissors I'm currently porting the changes to other versions and merge after that's done.

2023-10-18 17:25 UTC, merged