Add Epinio landing page
rancher/rancher-docs pull request #945
Opened 2023-10-17 20:16 UTC by btat

Fixes https://github.com/rancher/rancher-docs/issues/939

## Description

Adds a landing page for the Epinio integration.

2023-10-18 15:20 UTC, martyav commented
@btat Do all the other landing page PRs also need the 2.8 milestone?

2023-10-19 15:16 UTC, martyav requested changes

2023-10-19 15:16 UTC, martyav commented on versioned_docs/version-2.8/integrations-in-rancher/epinio.md
> +On top of the specific support service, Rancher Prime customers of Epinio should expect better integration of Epinio with other Rancher projects such as:
```suggestion
Alongside Rancher-specific tech support, customers who combine a Rancher Prime subscription with Epinio can expect enhanced performance in the following areas: 
```

2023-10-19 15:16 UTC, martyav commented on versioned_docs/version-2.8/integrations-in-rancher/epinio.md
> +Epinio lets developers go from application sources to URL in a single step. Epinio is an Application Development Platform. It deploys on Kubernetes and lets application developers and operators work
```suggestion
Epinio is a Kubernetes-based Application Development Platform. It helps operators and developers collaborate without conflict, and accelerates the development process. With Epinio, teams can move from application sources to a live URL in a single step.
```

2023-10-19 15:16 UTC, martyav commented on versioned_docs/version-2.8/integrations-in-rancher/epinio.md
> +Epinio's integration with Rancher lets developers quickly start using it without having to deal with the installation process or the configuration. You can install Epinio from the Apps. Currently the
```suggestion
Epinio's integration with Rancher gives developers a jump start, without having to deal with a lengthy installation process or configuration. You can install Epinio directly from the Rancher UI's Apps page. Currently the team is working to have Epinio available as a Rancher extension.
```

2023-10-19 15:16 UTC, martyav commented on versioned_docs/version-2.8/integrations-in-rancher/epinio.md
> +- Integrating Neuvector/Kubewarden with Epinio.
```suggestion
- Integration with Neuvector and Kubewarden.
```

2023-10-19 15:16 UTC, martyav commented on versioned_docs/version-2.8/integrations-in-rancher/epinio.md
> +- Using a custom Chart template with the right annotations to integrate with monitoring for example.
```suggestion
- Using a custom Chart template with the right annotations to integrate with monitoring for example.
```

Not sure how to revise this to make it snappier..."Custom Helm chart templates for monitoring and other key tools"?

2023-10-19 15:16 UTC, martyav commented on versioned_docs/version-2.8/integrations-in-rancher/epinio.md
> +- A better service marketplace.
```suggestion
- Improved service marketplace.
```

2023-10-19 21:51 UTC, btat commented
Per discussion with Guna, we're proceeding to merge so stakeholders are able to preview the initial design/update. We'll continue to improve/iterate and address any feedback post-merge.

2023-10-19 21:52 UTC, merged