Add session management section
rancher/rancher-docs pull request #981
Opened 2023-11-13 22:43 UTC by pdellamore

## Description
This PR will create a new section inside Rancher Security Best Practices adding security recommendations for RM deployments that might need additional security controls.

2023-11-14 09:51 UTC, pjbgf commented on docs/reference-guides/rancher-security/rancher-security-best-practices.md
> +If your Rancher instance is deployed in an environment which requires additional security requirements, use a Layer 7 firewall behind it.
```suggestion
If such features are required, we recommend the combined use of Layer 7 firewalls and [external authentication providers](https://ranchermanager.docs.rancher.com/v2.7/pages-for-subheaders/authentication-config#external-vs-local-authentication).

```

2023-11-14 09:51 UTC, pjbgf commented on docs/reference-guides/rancher-security/rancher-security-best-practices.md
> +Some environments may require extra security controls regarding session management. The upstream Rancher instance does not implement a limit for active sessions for a specific user.
```suggestion
Some environments may require additional security controls regarding session management, for example, limiting the amount of concurrent active sessions for a given user or restricting where those sessions can be initiated from - to block specific geo-locations or impossible travel incidents. Such features are not supported out-of-the box in Rancher Manager. 
```

2023-11-15 18:14 UTC, macedogm requested changes

2023-11-15 18:14 UTC, macedogm commented on docs/reference-guides/rancher-security/rancher-security-best-practices.md
> +Some environments may require extra security controls regarding session management. The upstream Rancher instance does not implement a limit for active sessions for a specific user.
I like this suggestion ^, would only suggest to simplify and remove the following part - `or impossible travel incidents`. It seems a bit too much for me and the geo-blocking mentioned earlier would already cover this IMO.

2023-11-15 18:14 UTC, macedogm commented on docs/reference-guides/rancher-security/rancher-security-best-practices.md
> +If your Rancher instance is deployed in an environment which requires additional security requirements, use a Layer 7 firewall behind it.
Would recommend to link against the latest version, instead of a specific version of the docs -> `https://ranchermanager.docs.rancher.com/pages-for-subheaders/authentication-config#external-vs-local-authentication`.

2023-11-15 18:14 UTC, macedogm commented
We should be good to merge this as soon as the comments are addressed.

2023-11-15 22:11 UTC, martyav requested changes

2023-11-15 22:11 UTC, martyav commented on docs/reference-guides/rancher-security/rancher-security-best-practices.md
> +### Session management
```suggestion
### Session Management
```

2023-11-15 22:12 UTC, martyav commented on docs/reference-guides/rancher-security/rancher-security-best-practices.md
> +If you require such features, combine Layer 7 firewalls with [external authentication providers](../../pages-for-subheaders/authentication-config#external-vs-local-authentication.md).
```suggestion
If you require such features, combine Layer 7 firewalls with [external authentication providers](../../pages-for-subheaders/authentication-config.md#external-vs-local-authentication).
```

2023-11-15 22:13 UTC, martyav approved these changes

2023-11-16 12:46 UTC, macedogm approved these changes
Pointed a small nit that should not affect visually the rendered page.

2023-11-16 12:46 UTC, macedogm commented on docs/reference-guides/rancher-security/rancher-security-best-practices.md
> +Some environments may require additional security controls for session management. For example, you may want to limit users' concurrent active sessions  or restrict which geolocations those sessions
```suggestion
Some environments may require additional security controls for session management. For example, you may want to limit users' concurrent active sessions or restrict which geolocations those sessions can be initiated from. Such features are not supported by Rancher out of the box. 
```

2023-11-16 16:02 UTC, martyav commented
Just versioned the page. Let's merge after the test deploy

2023-11-16 16:35 UTC, merged